import type { PromptResourceDocument } from "./types.js";

export const WORKFLOW_RUNTIME_VALIDATION_EXPERIENCE_ID = "workflow-runtime-artifact-validation";
export const PLANNER_READINESS_CONTRACT_EXPERIENCE_ID = "planner-readiness-contract";
export const AGENT_CAPABILITY_DESIGN_RULE_ID = "agent-capability-design-contract";

const AGENT_CAPABILITY_DESIGN_RULE_V1 = [
  "Agent设计规则：能力完备性与Pi装配一致性",
  "",
  "适用场景：设计、修改或审核Chat中的Workflow Agent，包括其System Prompt、自定义Prompt、Model、Thinking Level、Skill、Tool、Extension、Plugin、Session上下文、输入输出合同和Workflow边界。",
  "",
  "必须遵守：",
  "1. 先定义Agent的任务结果：写清使命、输入、预期输出、职责范围、非目标、授权边界和可验证的完成条件；不能只写角色名称或宽泛行为口号。",
  "2. 列出完成使命所需的信息及其事实源：当前Session、Memory、Project Context、Rule、Experience、Skill、Tool、用户补充或Executor调查。只有用户能决定且会改变结果的信息才向用户提问。",
  "3. 为每项职责核对可达能力：Agent实际装配的Model、Thinking Level、Tool、Skill和上下文必须足以完成该职责；需要Tool Calling、结构化输出或较长上下文时要用真实模型行为验证。禁止System Prompt要求使用未注册、未激活、不可读取或当前模型无法调用的能力。",
  "4. System Prompt负责身份、目标、基本决策逻辑、边界和输出协议；Rule承载可复用约束；Skill承载任务方法；Tool描述动作、适用时机、输入、输出和限制；Memory只提供历史事实。不要靠重复提示词掩盖能力缺口。",
  "5. 语义判断留给Agent，确定性的状态机、授权门禁、输入校验、重试、持久化和阶段交接留给Workflow与Backend；不得以强制Tool调用代替合理的Agent决策，也不得只靠提示词承担安全或协议门禁。",
  "6. Agent应使用完成当前任务所需的最小权限。读取、调查、修改、对外动作和不可逆动作要分别授权；计划获批不自动扩大Executor的动作权限。",
  "7. 输入输出合同必须与上下游一致：明确缺少信息时的状态、正常交付结构、证据与来源、失败表达、人工审核点以及下一Agent收到的版本化任务书。",
  "8. 所有能力必须走Chat统一装配链：配置与资源由Backend解析，检查与执行都使用resolveWorkflowAgentDefinition()和createWorkflowAgentSession()，最终由Pi ResourceLoader、AgentSession和SessionManager加载及记录。不得为单个Agent建立旁路运行时或前端事实源。",
  "9. 设计完成后至少用代表性场景验证：已有上下文、需要Memory、需要Skill或只读Project检查、需要Executor调查、确有阻塞问题、Tool无结果或失败。每个场景都要检查Agent是否掌握足够信息、是否越权、是否如实描述已用能力、是否交付可验收结果。",
  "10. 评审时同时检查提示词和真实装配结果；‘配置中写了’、‘资源能被发现’或‘相邻测试通过’都不能证明模型在实际Session中看得到并能使用。关键合同必须有自动化回归门禁。",
  "",
  "评审输出必须指出：使命是否完整、信息是否可得、能力是否可达、边界是否正确、上下游合同是否闭合、真实Runtime如何验证，以及仍缺失的配置或测试。",
].join("\n");

const WORKFLOW_RUNTIME_VALIDATION_EXPERIENCE_V1 = [
  "开发经验案例：Workflow Builder 丢失 JSON import attribute",
  "",
  "适用场景：修改 src/workflows、Workflow/Step 可达模块、Workflow SDK、Builder patch、Agent 配置装载或运行状态处理时。",
  "",
  "已发生现象：源码使用 `with { type: \"json\" }` 正确导入 agent.json，但 @workflow/builders 的 SWC 转换产物删除了 import attribute。Node 在 Workflow Runtime 装载 Step 前抛出 ERR_IMPORT_ATTRIBUTE_MISSING；前端只看到‘正在等待模型’，本地队列重试耗尽后 Run 仍未进入失败终态。",
  "",
  "正确姿势：",
  "1. 不把源码可导入、TypeScript通过或构建成功等同于 Workflow Runtime 可执行。",
  "2. Workflow/Step 可达模块使用特殊语法或非代码资源时，必须检查实际 Builder 转换产物。",
  "3. 修改 Workflow 执行链后，必须运行真实本地 Runtime smoke test，确认产生 stage_start 并最终进入 completed、failed 或 cancelled。",
  "4. 队列、模块装载或 Agent 创建失败必须向 Run 和前端传播明确失败；禁止长期停留在 running/waiting 状态。",
  "5. 每个线上或开发故障都要补回归测试；只有文档记录、没有机器门禁，不能视为完成复盘。",
  "",
  "本案例的机器门禁：@workflow/builders 转换必须保留 import attribute；内置经验必须可被前端发现、勾选，并通过 Agent 统一装配进入 chat_agent_custom_instructions 区域。",
].join("\n");

const WORKFLOW_RUNTIME_VALIDATION_EXPERIENCE_V2 = [
  "开发经验案例：Workflow 开发产物外置 Agent JSON，导致 Run 永久等待",
  "",
  "适用场景：修改 src/workflows、Workflow/Step 可达模块、Workflow SDK、Builder patch、Agent 配置装载、开发启动链或运行状态处理时。",
  "",
  "已发生现象：源码中的 agent.json 导入合法，生产构建与生产 Runtime smoke test也通过，但 `nitro dev` 生成的 `node_modules/.nitro/workflow/steps.mjs` 把 5 份本地 Agent JSON 留成了不带 attribute 的外部 import。Node 在 Step 装载、Pi Agent创建之前抛出 ERR_IMPORT_ATTRIBUTE_MISSING；前端长期显示‘正在等待模型’，同一队列消息持续 HTTP 500 重试。",
  "",
  "直接根因：开发模式的 Workflow Builder 会外置非 Step 模块，并直接从磁盘加载 Step bundle。它已经打包 Step 可达的本地 TypeScript，却没有把这些模块继续引用的本地 JSON 纳入 bundle；生产模式还有后续 Nitro/Rolldown 构建，会把 JSON 内联，所以只测生产产物无法发现开发链故障。SWC层也必须保留 import attribute，作为仍需外置 JSON 时的语法保障。",
  "",
  "正确姿势：",
  "1. 分别验证源码、Builder单层转换、完整开发 Step bundle、生产 bundle和真实 Runtime；任何一层通过都不能代替下一层。",
  "2. 开发模式直接加载的 Step产物必须自包含所有可达本地代码和 JSON配置，不依赖Node去装载源码目录中的原始JSON。",
  "3. 测试必须调用实际解析到的 Nitro LocalBuilder(dev=true)，检查完整steps.mjs中没有Agent JSON外部import，并让Node实际import该产物。",
  "4. 修改Workflow执行链后，仍要运行真实本地Runtime smoke test，确认产生stage_start并最终进入completed、failed或cancelled。",
  "5. 队列、模块装载或Agent创建失败必须向Run和前端传播明确失败；禁止长期停留在running/waiting状态。",
  "6. 每个故障都要补可复现的机器门禁；只测更容易通过的相邻链路不算完成复盘。",
  "",
  "本案例的机器门禁：SWC保留import attribute；Nitro开发Step bundle内联5份Agent JSON并可被Node装载；生产Built Server提交真实Workflow Run；案例自动归档、可在前端勾选，并进入chat_agent_custom_instructions区域。",
].join("\n");

const WORKFLOW_RUNTIME_VALIDATION_EXPERIENCE_V3 = [
  "开发经验案例：开发模式必须打通 Frontend Run 到 Pi SDK 的完整链路",
  "",
  "适用场景：修改 Workflow 构建、Agent 装配、内置 Skill/Tool/Prompt 资源、Backend 初始化或开发启动链时。",
  "",
  "第二次暴露的问题：Agent JSON修复后，Frontend请求已经进入Workflow，Agent节点也开始执行并调用createWorkflowAgentSession，但Step在读取被错误建模成全局运行时资源的chat-architecture/SKILL.md时失败，Pi AgentSession和模型仍未真正运行。Nitro dev直接加载Workflow Step bundle，其中的nitro/storage是stub。",
  "",
  "正确职责：chat-architecture属于Chat Project的.chat/skills资源，只通过标准Project资源路径发现，不打包、不物化、不全局注入。memory和rule-library属于Workflow实现的私有Skill；Backend控制面在接受Workflow前准备它们，Workflow Step不依赖Nitro宿主资源API。",
  "",
  "端到端完成标准：启动真实Nitro dev和隔离Chat Home，使用本地零成本假模型，通过Frontend使用的POST /runs合同提交请求；必须依次观察Workflow accepted、Agent节点启动、Pi AgentSession创建、模型选择，并由GET /runs/:id确认completed和确定结果。只检查Builder产物、只测生产Server或只看到HTTP 202都不能声称修复完成。",
  "",
  "本案例的机器门禁：pnpm verify固定运行test:dev；测试使用独立Nitro buildDir、Chat Home、Project和本地假模型，不访问正式模型、不污染用户数据，也不与正在运行的开发服务共享构建产物。",
].join("\n");

const WORKFLOW_RUNTIME_VALIDATION_EXPERIENCE_V4 = [
  "开发经验案例：Workflow Step复用与Registry依赖必须保持运行时边界",
  "",
  "适用场景：复用Workflow Step实现、新增prepareAgentSession或Pi Custom Tool、修改中央Workflow Registry、增加Workflow私有Skill或引入子Workflow调用时。",
  "",
  "已发生现象：通用规划helper作为普通export留在steps.ts后，Workflow Builder为了保留普通导出，把Pi、Mem0和Node依赖带进Workflow沙箱并产生257个构建错误。拆分后，Registry可达Tool对Registry与Chat Config的反向静态依赖又导致Nitro开发Worker报init_chat_config/init_registry is not a function。Worker启动后，未预先物化的workflow-delegation Skill在开发Step中因nitro/storage stub读取失败。",
  "",
  "正确姿势：",
  "1. Workflow编排只导入Hook、纯Workflow逻辑和use step代理；被编排导入的Step模块不同时导出普通Node运行时代码。",
  "2. 通用Step实现放入独立Node Runtime模块，由薄Step入口调用；文件系统、Pi SDK、Chat Config和执行服务不能进入Workflow沙箱图。",
  "3. Registry可达的Agent Runtime与Tool不能反向静态导入Registry或Chat Config；目标校验和持久默认由执行Step解析后以窄接口注入。",
  "4. Workflow私有Skill由Backend初始化在Step运行前物化；执行与Resolve仍共用同一prepareAgentSession装配。",
  "5. 子Workflow必须用真实Pi Tool Calling验证：人工批准前0个子Session，批准后精确创建计划数量的独立Session，并校验每个Run与Invocation ID。",
  "",
  "本案例的机器门禁：LocalBuilder开发bundle可构建并由Node加载；三个Workflow私有Skill预先准备；Built Server验证Coordinator的Skill/Tool装配；pnpm test:dev让Coordinator同轮发出5个workflow_call并完成5个独立子Workflow。",
].join("\n");

const WORKFLOW_RUNTIME_VALIDATION_EXPERIENCE_V5 = [
  "开发经验案例：部署运行时版本必须参与源码兼容验证",
  "",
  "适用场景：修改由Node.js直接装载的TypeScript/JavaScript源码、Workflow编排、CI运行时、Linux部署基线或使用较新的语言语法时。",
  "",
  "已发生现象：macOS开发机使用Node.js 24.8.0，完整pnpm verify通过；GitHub CI与Linux部署固定Node.js 22.19.0，在装载两个人工审核Workflow的using decisionHook声明时抛出SyntaxError，导致11个Backend测试无法启动。此前Pi准备失败又长期遮蔽了这层错误。",
  "",
  "正确姿势：",
  "1. CI、自动部署和文档共享同一Node.js固定版本；本地较新版本通过不能替代生产基线验证。",
  "2. 涉及新语法时，必须检查代码是经构建转换还是由固定Node.js直接装载；类型检查和较新Node运行成功都不是语法兼容证明。",
  "3. Workflow Hook使用公开幂等dispose()和普通try/finally覆盖完整审核轮次，确保冲突、等待、修订、批准返回和异常路径都释放资源。",
  "4. CI分阶段显示Submodule、依赖准备和应用验证，避免前置故障长期遮蔽后续运行时问题。",
  "",
  "本案例的机器门禁：源码测试禁止两个审核Workflow重新引入声明级using/await using，并要求finally调用decisionHook.dispose()；Node.js 22.19.0 CI运行完整pnpm verify。",
].join("\n");

const PLANNER_READINESS_CONTRACT_EXPERIENCE_V1 = [
  "开发经验案例：Planner必须区分任务澄清与可执行计划",
  "",
  "适用场景：修改Planning Execution Workflow、Planner Prompt、审核合同、Executor交接或任何带人工审核的多Agent串行流程时。",
  "",
  "已发生现象：Planner把口味、预算、冲煮方式等尚未确认的关键需求写成Executor第一步，同时把计划提交为可批准。批准后Executor只能猜测或再次询问；询问产生回复后当前Run结束，下一条用户消息会启动新Run，无法恢复原Executor Stage。",
  "",
  "正确姿势：",
  "1. Planner先覆盖背景、目标、交付物、范围、约束、依赖、授权边界和验收标准。",
  "2. 区分用户已确认事实、Executor可调查事实、非阻塞假设和只有用户能决定的阻塞信息。",
  "3. 阻塞信息必须输出needs_clarification并在Review Task闭环；不得下放给Executor，也不得展示批准入口。",
  "4. 只有ready_for_review进入Executor；Backend必须拒绝对澄清稿提交的批准，不能只依赖前端隐藏按钮。",
  "5. Executor接收版本化任务书，其中包含用户真实请求、批准版本、批准计划、调查职责、授权边界和完成报告要求。",
  "6. 购买、发布、删除、付款等动作要区分计划审核与最终动作授权；计划通过不自动扩大授权。",
  "",
  "本案例的机器门禁：严格解析Planner就绪元数据；前后端共同校验阻塞问题；真实pnpm test:dev先拒绝澄清稿批准，再补充信息、生成可执行计划并完成Executor回合。",
].join("\n");

/**
 * Product-owned rules and experiences are seeded into the Personal Prompt resource store.
 * After seeding they use the same versioned storage, discovery and Agent selection
 * path as user-created rules and experiences.
 */
export const BUILT_IN_PERSONAL_PROMPT_RESOURCES = [
  {
    schemaVersion: 1,
    id: AGENT_CAPABILITY_DESIGN_RULE_ID,
    revisions: [{
      schemaVersion: 1,
      id: AGENT_CAPABILITY_DESIGN_RULE_ID,
      revision: 1,
      kind: "rule",
      title: "Agent能力完备性与Pi装配一致性",
      purpose: "确保Agent的使命、信息、能力、权限、上下游合同和真实Pi装配共同构成可运行、可验证的完整设计。",
      content: AGENT_CAPABILITY_DESIGN_RULE_V1,
      tags: ["agent-design", "architecture", "capability", "prompt", "skill", "tool", "pi-agent", "workflow", "quality"],
      status: "active",
      sources: [{
        type: "manual",
        entryIds: [],
        context: "源自2026-09-01对Planner、Memory Tool、Skill发现和Planning Execution Workflow装配链的系统复盘。",
        capturedAt: "2026-09-01T10:00:00.000Z",
      }],
      author: { type: "user" },
      createdAt: "2026-09-01T10:00:00.000Z",
    }],
  },
  {
    schemaVersion: 1,
    id: WORKFLOW_RUNTIME_VALIDATION_EXPERIENCE_ID,
    revisions: [{
      schemaVersion: 1,
      id: WORKFLOW_RUNTIME_VALIDATION_EXPERIENCE_ID,
      revision: 1,
      kind: "experience",
      title: "Workflow 构建产物必须经过真实 Runtime 验证",
      purpose: "避免源码、类型检查和构建通过，但 Workflow 转换产物在实际运行时装载失败。",
      content: WORKFLOW_RUNTIME_VALIDATION_EXPERIENCE_V1,
      tags: ["development", "incident", "workflow", "runtime", "build-toolchain"],
      status: "active",
      sources: [{
        type: "manual",
        entryIds: [],
        context: "归档于 docs/development-experiences/workflow-builder-json-import-attribute.md；源自 2026-08-31 的本地 Workflow Runtime 故障复盘。",
        capturedAt: "2026-08-31T14:45:09.006Z",
      }],
      author: { type: "user" },
      createdAt: "2026-08-31T14:45:09.006Z",
    }, {
      schemaVersion: 1,
      id: WORKFLOW_RUNTIME_VALIDATION_EXPERIENCE_ID,
      revision: 2,
      kind: "experience",
      title: "Workflow 构建产物必须经过真实 Runtime 验证",
      purpose: "避免生产构建通过，但 Nitro 开发 Step 产物在实际运行时装载失败。",
      content: WORKFLOW_RUNTIME_VALIDATION_EXPERIENCE_V2,
      tags: ["development", "incident", "workflow", "runtime", "build-toolchain"],
      status: "active",
      sources: [{
        type: "manual",
        entryIds: [],
        context: "归档于 docs/development-experiences/workflow-builder-json-import-attribute.md；2026-09-01 根据 Nitro dev 实际产物补全根因与开发链门禁。",
        capturedAt: "2026-08-31T23:15:00.000Z",
      }],
      author: { type: "user" },
      createdAt: "2026-08-31T23:15:00.000Z",
    }, {
      schemaVersion: 1,
      id: WORKFLOW_RUNTIME_VALIDATION_EXPERIENCE_ID,
      revision: 3,
      kind: "experience",
      title: "Workflow 构建产物必须经过真实 Runtime 验证",
      purpose: "要求开发链从 Frontend Run 合同一直验证到 Pi SDK 和确定的本地模型结果。",
      content: WORKFLOW_RUNTIME_VALIDATION_EXPERIENCE_V3,
      tags: ["development", "incident", "workflow", "runtime", "build-toolchain", "e2e"],
      status: "active",
      sources: [{
        type: "manual",
        entryIds: [],
        context: "归档于 docs/development-experiences/workflow-builder-json-import-attribute.md；2026-09-01 根据 Nitro dev Skill资源故障补充完整开发端到端门禁。",
        capturedAt: "2026-08-31T23:44:00.000Z",
      }],
      author: { type: "user" },
      createdAt: "2026-08-31T23:44:00.000Z",
    }, {
      schemaVersion: 1,
      id: WORKFLOW_RUNTIME_VALIDATION_EXPERIENCE_ID,
      revision: 4,
      kind: "experience",
      title: "Workflow 构建产物必须经过真实 Runtime 验证",
      purpose: "确保Workflow/Step、Registry、Agent Tool和私有Skill保持正确运行时边界，并用真实子Workflow拓扑验证。",
      content: WORKFLOW_RUNTIME_VALIDATION_EXPERIENCE_V4,
      tags: ["development", "incident", "workflow", "runtime", "build-toolchain", "dependency-boundary", "subworkflow"],
      status: "active",
      sources: [{
        type: "manual",
        entryIds: [],
        context: "归档于 docs/development-experiences/workflow-step-runtime-boundary.md；源自2026-09-03 Workflow调用Workflow实现中的Builder、Registry初始化和私有Skill故障复盘。",
        capturedAt: "2026-09-03T07:30:00.000Z",
      }],
      author: { type: "user" },
      createdAt: "2026-09-03T07:30:00.000Z",
    }, {
      schemaVersion: 1,
      id: WORKFLOW_RUNTIME_VALIDATION_EXPERIENCE_ID,
      revision: 5,
      kind: "experience",
      title: "Workflow 构建产物必须经过真实 Runtime 验证",
      purpose: "确保较新的本地Node.js不会掩盖CI与Linux部署固定版本无法解析或执行的Workflow源码。",
      content: WORKFLOW_RUNTIME_VALIDATION_EXPERIENCE_V5,
      tags: ["development", "incident", "workflow", "runtime", "build-toolchain", "deployment", "ci", "nodejs", "runtime-compatibility"],
      status: "active",
      sources: [{
        type: "manual",
        entryIds: [],
        context: "归档于 docs/development-experiences/deployment-runtime-version-parity.md；源自2026-09-04公开Submodule部署CI复盘。",
        capturedAt: "2026-09-04T11:40:00.000Z",
      }],
      author: { type: "user" },
      createdAt: "2026-09-04T11:40:00.000Z",
    }],
  },
  {
    schemaVersion: 1,
    id: PLANNER_READINESS_CONTRACT_EXPERIENCE_ID,
    revisions: [{
      schemaVersion: 1,
      id: PLANNER_READINESS_CONTRACT_EXPERIENCE_ID,
      revision: 1,
      kind: "experience",
      title: "Planner必须区分任务澄清与可执行计划",
      purpose: "避免把尚未解决的用户决策下放给Executor，并防止不完整计划被批准执行。",
      content: PLANNER_READINESS_CONTRACT_EXPERIENCE_V1,
      tags: ["development", "incident", "workflow", "planning", "human-review", "agent-contract"],
      status: "active",
      sources: [{
        type: "manual",
        entryIds: [],
        context: "归档于 docs/development-experiences/planner-readiness-contract.md；源自2026-09-01购买咖啡豆规划Session复盘。",
        capturedAt: "2026-09-01T07:30:00.000Z",
      }],
      author: { type: "user" },
      createdAt: "2026-09-01T07:30:00.000Z",
    }],
  },
] as const satisfies readonly PromptResourceDocument[];
