import type { ClientContext } from "@deepseek-ai/dsh-client-runtime/client";

const STYLE_ID = "chat-memory-management-v1";
const CSS = `
.lifeos-memory-management{box-sizing:border-box;width:100%;max-width:900px;margin:0 auto;padding:20px;color:var(--dsw-alias-label-primary);font-size:13px}.lifeos-memory-management>header,.lifeos-memory-detail>header,.lifeos-memory-import-preview>header,.lifeos-memory-comparison-result>header,.lifeos-memory-import-history article>header{display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.lifeos-memory-management h1,.lifeos-memory-management h2,.lifeos-memory-detail h2{margin:0;font-size:20px}.lifeos-memory-management>header p{margin:6px 0 0;color:var(--dsw-alias-label-secondary);line-height:1.55}.lifeos-memory-management button,.lifeos-memory-management select,.lifeos-memory-management input,.lifeos-memory-management textarea{font:inherit}.lifeos-memory-management button,.lifeos-memory-management select{min-height:36px;padding:0 12px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:transparent;color:var(--dsw-alias-label-primary);cursor:pointer}.lifeos-memory-management button:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover)}.lifeos-memory-management button:disabled,.lifeos-memory-management select:disabled,.lifeos-memory-management input:disabled,.lifeos-memory-management textarea:disabled{opacity:.5;cursor:default}.lifeos-memory-management button:focus-visible,.lifeos-memory-management select:focus-visible,.lifeos-memory-management input:focus-visible,.lifeos-memory-management textarea:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary);outline-offset:2px}.lifeos-memory-management .lifeos-primary{border-color:transparent;background:var(--dsw-alias-button-info-fill);color:var(--dsw-alias-label-primary-foreground)}
.lifeos-memory-tabs{display:flex;gap:6px;margin:20px 0 14px;border-bottom:1px solid var(--dsw-alias-border-l1)}.lifeos-memory-tabs button{margin-bottom:-1px;border-color:transparent;border-bottom-color:var(--dsw-alias-border-l1);border-radius:8px 8px 0 0}.lifeos-memory-tabs button[aria-selected="true"]{border-bottom-color:var(--dsw-alias-state-business-primary);color:var(--dsw-alias-state-business-primary)}.lifeos-memory-error{padding:10px 12px;border:1px solid var(--dsw-alias-state-error-primary);border-radius:8px;color:var(--dsw-alias-state-error-primary)}.lifeos-memory-note{margin:0;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:1.6}.lifeos-memory-empty{margin:0;padding:26px;border:1px dashed var(--dsw-alias-border-l2);border-radius:10px;color:var(--dsw-alias-label-secondary);text-align:center}
.lifeos-memory-list{display:grid;gap:10px}.lifeos-memory-list-card{display:flex;align-items:center;justify-content:space-between;gap:12px;width:100%;height:auto!important;min-height:70px!important;padding:12px 14px!important;text-align:left}.lifeos-memory-list-card>span{display:grid;min-width:0;gap:5px}.lifeos-memory-list-card strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.lifeos-memory-list-card small,.lifeos-memory-list-card code{color:var(--dsw-alias-label-tertiary);font-size:11px}.lifeos-memory-list-card code{flex:none}
.lifeos-memory-detail,.lifeos-memory-panel{display:grid;gap:14px}.lifeos-memory-detail>header small,.lifeos-memory-detail dt,.lifeos-memory-import-preview small{color:var(--dsw-alias-label-tertiary);font-size:11px}.lifeos-memory-detail>dl{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:0}.lifeos-memory-detail>dl>div{display:grid;grid-template-columns:82px minmax(0,1fr);gap:8px}.lifeos-memory-detail dd{min-width:0;margin:0;overflow-wrap:anywhere}.lifeos-memory-candidate-items{display:grid;gap:9px}.lifeos-memory-candidate-items details,.lifeos-memory-comparison-result article,.lifeos-memory-import-preview,.lifeos-memory-import-history article{overflow:hidden;border:1px solid var(--dsw-alias-border-l1);border-radius:10px;background:var(--dsw-alias-bg-base)}.lifeos-memory-candidate-items summary,.lifeos-memory-comparison-result article>header,.lifeos-memory-import-preview>header,.lifeos-memory-import-history article>header{padding:11px 13px;cursor:pointer}.lifeos-memory-candidate-items summary{display:flex;align-items:center;justify-content:space-between;gap:12px}.lifeos-memory-candidate-items summary span{display:grid;gap:3px}.lifeos-memory-candidate-items summary small,.lifeos-memory-candidate-items summary code{color:var(--dsw-alias-label-tertiary);font-size:10px}.lifeos-memory-labels,.lifeos-memory-evidence{display:flex;flex-wrap:wrap;gap:6px;padding:0 13px 10px}.lifeos-memory-labels span,.lifeos-memory-evidence code{padding:2px 6px;border-radius:999px;background:var(--dsw-specific-tip);color:var(--dsw-alias-label-secondary);font-size:10px}.lifeos-memory-evidence{align-items:center;border-top:1px solid var(--dsw-alias-border-l1);padding-top:10px}.lifeos-memory-evidence strong{font-size:11px}.lifeos-memory-candidate-items pre,.lifeos-memory-comparison-result pre,.lifeos-memory-import-preview pre{box-sizing:border-box;max-height:360px;margin:0;padding:12px 13px;overflow:auto;border-top:1px solid var(--dsw-alias-border-l1);background:var(--dsw-specific-tip);font:11px/1.6 ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace;white-space:pre-wrap;overflow-wrap:anywhere}
.lifeos-memory-actions{display:flex;flex-wrap:wrap;align-items:end;justify-content:space-between;gap:10px}.lifeos-memory-actions>label,.lifeos-memory-field{display:grid;min-width:min(100%,360px);gap:6px;color:var(--dsw-alias-label-secondary);font-size:11px}.lifeos-memory-actions>label{flex:1}.lifeos-memory-actions textarea,.lifeos-memory-field textarea{box-sizing:border-box;width:100%;min-height:74px;padding:9px 10px;resize:vertical;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary)}.lifeos-memory-actions>div{display:flex;flex-wrap:wrap;gap:8px}.lifeos-memory-source-picker{display:grid;grid-template-columns:minmax(130px,.7fr) minmax(220px,1.4fr) auto;gap:10px;align-items:end}.lifeos-memory-source-picker label,.lifeos-memory-field{color:var(--dsw-alias-label-secondary)}.lifeos-memory-source-picker label{display:grid;gap:6px;font-size:11px}.lifeos-memory-source-picker select,.lifeos-memory-field select{box-sizing:border-box;width:100%;background:var(--dsw-alias-bg-base)}.lifeos-memory-provider-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:0;padding:12px;border:1px solid var(--dsw-alias-border-l1);border-radius:10px}.lifeos-memory-provider-options legend{padding:0 5px;font-size:12px;font-weight:600}.lifeos-memory-provider-options label{display:flex;min-width:0;align-items:center;gap:7px;padding:8px;border-radius:7px;background:var(--dsw-specific-tip)}.lifeos-memory-provider-options span{min-width:0;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.lifeos-memory-provider-options code{color:var(--dsw-alias-label-tertiary);font-size:10px}.lifeos-memory-comparison-result{display:grid;gap:10px}.lifeos-memory-comparison-result>header{align-items:baseline;padding:0}.lifeos-memory-comparison-result>header span{color:var(--dsw-alias-label-tertiary);font-size:11px}.lifeos-memory-comparison-result article>header{align-items:baseline;border-bottom:1px solid var(--dsw-alias-border-l1);cursor:default}.lifeos-memory-comparison-result article>header code{color:var(--dsw-alias-label-tertiary);font-size:10px}.lifeos-memory-comparison-result article>p{margin:0;padding:0 13px 11px;color:var(--dsw-alias-label-secondary)}.lifeos-memory-comparison-result article details{border-top:1px solid var(--dsw-alias-border-l1)}.lifeos-memory-comparison-result article summary{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 13px;cursor:pointer}.lifeos-memory-comparison-result article summary small{color:var(--dsw-alias-label-tertiary);font-size:10px}.lifeos-memory-pairwise{padding:12px;border:1px solid var(--dsw-alias-border-l1);border-radius:10px;background:var(--dsw-specific-tip)}.lifeos-memory-pairwise p{margin:7px 0 0;color:var(--dsw-alias-label-secondary);font-size:11px;line-height:1.55}
.lifeos-memory-import-preview{display:grid;gap:0}.lifeos-memory-import-preview>header{cursor:default}.lifeos-memory-import-preview>header>div{display:grid;gap:4px}.lifeos-memory-import-preview>header>span{color:var(--dsw-alias-label-secondary);font-size:11px}.lifeos-memory-import-preview>div{display:grid}.lifeos-memory-import-preview details{border-top:1px solid var(--dsw-alias-border-l1)}.lifeos-memory-import-preview summary{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 13px;cursor:pointer}.lifeos-memory-import-preview summary small{color:var(--dsw-alias-label-tertiary);font-size:10px}.lifeos-memory-import-preview footer{padding:12px 13px;border-top:1px solid var(--dsw-alias-border-l1)}.lifeos-memory-import-history{display:grid;gap:9px;margin-top:8px}.lifeos-memory-import-history h2{font-size:15px}.lifeos-memory-import-history article>header{align-items:baseline}.lifeos-memory-import-history article>header span{padding:3px 7px;border-radius:999px;background:var(--dsw-specific-tip);color:var(--dsw-alias-label-secondary);font-size:10px}.lifeos-memory-import-history article>header span[data-status="needs_attention"]{color:var(--dsw-alias-state-warning-primary)}.lifeos-memory-import-history article>p{margin:0;padding:0 13px 12px;color:var(--dsw-alias-label-secondary);font-size:11px}
@media(max-width:650px){.lifeos-memory-management{padding:14px 12px}.lifeos-memory-management>header,.lifeos-memory-detail>header{display:grid}.lifeos-memory-management button{min-height:42px}.lifeos-memory-tabs{overflow:auto}.lifeos-memory-tabs button{white-space:nowrap}.lifeos-memory-detail>dl{grid-template-columns:1fr}.lifeos-memory-source-picker{grid-template-columns:1fr}.lifeos-memory-provider-options{grid-template-columns:1fr}.lifeos-memory-actions{display:grid}.lifeos-memory-actions>div{display:grid;grid-template-columns:1fr}.lifeos-memory-actions>div button{width:100%}.lifeos-memory-list-card strong{white-space:normal}.lifeos-memory-import-preview>header,.lifeos-memory-import-preview summary{align-items:flex-start;display:grid}.lifeos-memory-comparison-result article>header{display:grid}}
`;

export function installMemoryManagementStyles(ctx: ClientContext): void {
  ctx.effect(() => {
    if (document.querySelector(`style[data-plugin-css="${STYLE_ID}"]`) !== null)
      return () => undefined;
    const element = document.createElement("style");
    element.dataset.pluginCss = STYLE_ID;
    element.textContent = CSS;
    document.head.append(element);
    return () => element.remove();
  }, "lifeos bridge: memory management styles");
}
