import type { ClientContext } from "@deepseek-ai/dsh-client-runtime/client";

const STYLE_ID = "chat-prompt-studio-v1";
const CSS = `
.lifeos-prompt-studio,.lifeos-prompt-studio-detail{box-sizing:border-box;width:100%;max-width:760px;margin:0 auto;padding:20px;color:var(--dsw-alias-label-primary);font-size:13px}
.lifeos-prompt-studio-header,.lifeos-prompt-studio-detail>header{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.lifeos-prompt-studio h1,.lifeos-prompt-studio h2,.lifeos-prompt-studio-detail h2{margin:0;font-size:20px}.lifeos-prompt-studio-header p{margin:6px 0 0;color:var(--dsw-alias-label-secondary);line-height:1.55}.lifeos-prompt-studio button,.lifeos-prompt-studio-detail button,.lifeos-prompt-studio select,.lifeos-prompt-studio-detail select{min-height:36px;padding:0 12px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:transparent;color:var(--dsw-alias-label-primary);font:inherit;cursor:pointer}.lifeos-prompt-studio button:hover:not(:disabled),.lifeos-prompt-studio-detail button:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover)}.lifeos-prompt-studio button:focus-visible,.lifeos-prompt-studio-detail button:focus-visible,.lifeos-prompt-studio input:focus-visible,.lifeos-prompt-studio textarea:focus-visible,.lifeos-prompt-studio select:focus-visible,.lifeos-prompt-studio-detail input:focus-visible,.lifeos-prompt-studio-detail textarea:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary);outline-offset:2px}.lifeos-prompt-studio button:disabled,.lifeos-prompt-studio-detail button:disabled{opacity:.45;cursor:default}.lifeos-prompt-studio .lifeos-primary,.lifeos-prompt-studio-detail .lifeos-primary{border-color:transparent;background:var(--dsw-alias-button-info-fill);color:var(--dsw-alias-label-primary-foreground)}
.lifeos-prompt-studio-tabs{display:flex;gap:6px;margin:20px 0 14px;border-bottom:1px solid var(--dsw-alias-border-l1)}.lifeos-prompt-studio-tabs button{margin-bottom:-1px;border-color:transparent;border-bottom-color:var(--dsw-alias-border-l1);border-radius:8px 8px 0 0}.lifeos-prompt-studio-tabs button[aria-selected="true"]{border-bottom-color:var(--dsw-alias-state-business-primary);color:var(--dsw-alias-state-business-primary)}
.lifeos-prompt-studio-error{padding:10px 12px;border:1px solid var(--dsw-alias-state-error-primary);border-radius:8px;color:var(--dsw-alias-state-error-primary)}.lifeos-prompt-studio-empty{padding:24px;color:var(--dsw-alias-label-secondary);text-align:center}
.lifeos-prompt-region-list,.lifeos-prompt-library-list{display:grid;gap:10px}.lifeos-prompt-region-list article{padding:13px 14px;border:1px solid var(--dsw-alias-border-l1);border-radius:10px;background:var(--dsw-alias-bg-base)}.lifeos-prompt-region-list article>header{display:flex;justify-content:space-between;gap:12px}.lifeos-prompt-region-list p{margin:8px 0;color:var(--dsw-alias-label-secondary);line-height:1.55}.lifeos-prompt-region-list footer{display:flex;align-items:flex-end;justify-content:space-between;gap:10px}.lifeos-prompt-region-list footer>div{display:flex;min-width:0;flex-wrap:wrap;gap:6px}.lifeos-prompt-region-list footer>div>*{padding:2px 6px;border-radius:999px;background:var(--dsw-specific-tip);color:var(--dsw-alias-label-tertiary);font-size:11px;overflow-wrap:anywhere}.lifeos-prompt-region-list footer>button{min-height:30px;flex:none;font-size:11px}
.lifeos-prompt-library-toolbar{display:flex;justify-content:space-between;gap:10px;margin-bottom:12px}.lifeos-prompt-library-card{display:grid!important;gap:7px!important;width:100%;height:auto!important;min-height:92px!important;padding:12px 13px!important;text-align:left}.lifeos-prompt-library-card>span{color:var(--dsw-alias-label-secondary)}.lifeos-prompt-library-card-title{display:flex;align-items:center;justify-content:space-between;gap:10px;color:var(--dsw-alias-label-primary)!important}.lifeos-prompt-library-card-title small{padding:2px 6px;border-radius:999px;background:var(--dsw-specific-tip);color:var(--dsw-alias-label-tertiary)}.lifeos-prompt-library-card-title small[data-kind="system"]{color:var(--dsw-alias-state-business-primary)}.lifeos-prompt-library-meta{display:flex;flex-wrap:wrap;gap:6px}.lifeos-prompt-library-meta code{font-size:10px}
.lifeos-prompt-studio-back{margin-bottom:16px}.lifeos-prompt-studio-detail>header small{color:var(--dsw-alias-label-tertiary)}.lifeos-prompt-studio-detail>header h2{margin-top:4px}.lifeos-prompt-studio-detail>header>span{padding:3px 8px;border-radius:999px;background:var(--dsw-specific-tip);color:var(--dsw-alias-label-secondary);font-size:11px}.lifeos-prompt-studio-facts{display:grid;gap:8px;margin:16px 0}.lifeos-prompt-studio-facts>div{display:grid;grid-template-columns:78px minmax(0,1fr);gap:10px}.lifeos-prompt-studio-facts dt{color:var(--dsw-alias-label-tertiary)}.lifeos-prompt-studio-facts dd{min-width:0;margin:0;overflow-wrap:anywhere}.lifeos-prompt-studio-facts code{font-size:10px}.lifeos-prompt-region-reference{display:flex;align-items:baseline;flex-wrap:wrap;gap:7px}.lifeos-prompt-region-reference code{color:var(--dsw-alias-label-tertiary)}.lifeos-prompt-source-link{display:flex!important;width:100%;height:auto!important;min-height:32px!important;align-items:center;justify-content:space-between;gap:10px;padding:6px 9px!important;text-align:left}.lifeos-prompt-source-link code{min-width:0;overflow-wrap:anywhere}.lifeos-prompt-source-link span{flex:none;color:var(--dsw-alias-state-business-primary);font-size:11px}.lifeos-prompt-studio-versions{display:flex;align-items:center;gap:12px;margin:14px 0}.lifeos-prompt-studio-versions>div{display:flex;flex-wrap:wrap;gap:6px}.lifeos-prompt-studio-versions button[aria-pressed="true"]{border-color:var(--dsw-alias-state-business-primary);color:var(--dsw-alias-state-business-primary)}.lifeos-prompt-studio-content,.lifeos-prompt-source-file{overflow:hidden;border:1px solid var(--dsw-alias-border-l1);border-radius:10px;background:var(--dsw-alias-bg-base)}.lifeos-prompt-studio-content>strong{display:block;padding:9px 12px;border-bottom:1px solid var(--dsw-alias-border-l1)}.lifeos-prompt-studio-content pre,.lifeos-prompt-source-file pre{box-sizing:border-box;max-height:50vh;margin:0;padding:14px;overflow:auto;color:var(--dsw-alias-label-primary);font:12px/1.65 ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace;white-space:pre-wrap;overflow-wrap:anywhere}.lifeos-prompt-source-file>header{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding:11px 13px;border-bottom:1px solid var(--dsw-alias-border-l1)}.lifeos-prompt-source-file>header p{margin:4px 0 0;color:var(--dsw-alias-label-tertiary);font-size:11px}.lifeos-prompt-source-file>header code{max-width:45%;color:var(--dsw-alias-label-secondary);font-size:10px;overflow-wrap:anywhere;text-align:right}
.lifeos-prompt-studio-editor{display:grid;gap:12px;margin:12px 0;padding:14px;border:1px solid var(--dsw-alias-border-l1);border-radius:10px;background:var(--dsw-alias-bg-base)}.lifeos-prompt-studio-editor label{display:grid;gap:6px;color:var(--dsw-alias-label-secondary)}.lifeos-prompt-studio-editor input,.lifeos-prompt-studio-editor textarea,.lifeos-prompt-studio-editor select{box-sizing:border-box;width:100%;min-height:38px;padding:8px 10px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);font:inherit}.lifeos-prompt-studio-editor textarea{min-height:220px;resize:vertical;font:12px/1.6 ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace}.lifeos-prompt-studio-editor p{margin:0;color:var(--dsw-alias-label-tertiary);font-size:11px}.lifeos-prompt-studio-actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:8px;margin-top:14px}
@media(max-width:600px){.lifeos-prompt-studio,.lifeos-prompt-studio-detail{padding:14px 12px}.lifeos-prompt-studio-header{display:grid}.lifeos-prompt-library-toolbar{align-items:stretch;flex-direction:column}.lifeos-prompt-studio button,.lifeos-prompt-studio-detail button{min-height:44px}.lifeos-prompt-region-list footer{align-items:stretch;flex-direction:column}.lifeos-prompt-region-list footer>button{width:100%}.lifeos-prompt-studio-actions{display:grid;grid-template-columns:1fr}.lifeos-prompt-studio-actions button{width:100%}.lifeos-prompt-studio-facts>div{grid-template-columns:64px minmax(0,1fr)}.lifeos-prompt-source-file>header{display:grid}.lifeos-prompt-source-file>header code{max-width:none;text-align:left}.lifeos-prompt-studio-editor textarea{font-size:16px}}
`;

export function installPromptStudioStyles(ctx: ClientContext): void {
  ctx.effect(() => {
    if (document.querySelector(`style[data-plugin-css="${STYLE_ID}"]`) !== null)
      return () => undefined;
    const element = document.createElement("style");
    element.dataset.pluginCss = STYLE_ID;
    element.textContent = CSS;
    document.head.append(element);
    return () => element.remove();
  }, "lifeos bridge: prompt studio styles");
}
