import React, { useState, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import * as Popover from '@radix-ui/react-popover';
import { Command } from 'cmdk';
import { IconArrowLeft, IconArrowRight, IconCheck, IconChevronDown, IconChevronRight, IconGitBranch, IconMessageCircle, IconBrain, IconTerminal2, IconNotes, IconShieldCheck, IconPhoto, IconStack2, IconSearch, IconAdjustmentsHorizontal, IconRestore, IconInfoCircle, IconSun, IconMoon, IconX, IconPlus, IconTool, IconFileText, IconBolt, IconCircleCheck, IconWorld, IconCode, IconPuzzle, IconEye, IconSettings, IconUser } from '@tabler/icons-react';
import '../../../frontend/src/styles/tokens.css';
import './style.css';
import './appearance.css';
import AppearancePicker from './AppearancePicker.jsx';
import { readAppearance, applyAppearance, appearanceStorageKey, themeById } from './themes.mjs';
import ComponentLab from './ComponentLab.jsx';

applyAppearance(readAppearance());

const models = [
  { id:'sonnet', name:'Claude Sonnet', provider:'Anthropic', letter:'A', tag:'均衡', image:true, context:'200K', limit:32000, thinking:['low','medium','high'], temperature:true },
  { id:'deepseek', name:'DeepSeek · Reasoner', provider:'DeepSeek', letter:'D', tag:'推理', image:false, context:'128K', limit:16000, thinking:['medium','high'], temperature:false },
  { id:'local', name:'Local · Fast', provider:'Local', letter:'L', tag:'轻量', image:false, context:'32K', limit:8192, thinking:[], temperature:true },
];
const scopeNames = { session:'当前会话', assistant:'助手默认', project:'项目默认' };
const scopeDescriptions = {session:'Nexus / 页面设计讨论',assistant:'Nexus / 默认执行配置',project:'Chat / 项目默认配置'};
const tabs=[['model','模型与生成'],['prompt','指令与输出'],['tools','工具与资源']];
const nodes={ execute:{name:'执行',agent:'执行 Agent',desc:'处理你的请求，完成工作并给出主要答复。',icon:IconTerminal2,role:'主要答复'}, remember:{name:'会话记忆',agent:'会话记忆 Agent',desc:'评估本轮值得保留的事实，维护当前会话的记忆。',icon:IconNotes,role:'内部维护'}, plan:{name:'规划',agent:'规划 Agent',desc:'理解需求，形成可以审核与执行的计划。',icon:IconBrain,role:'生成计划'}, review:{name:'人工审核',agent:'人工审核',desc:'在执行前，由你确认计划或提出修改意见。',icon:IconShieldCheck,role:'等待确认'} };
const toolCatalog=[['read','读取文件','查看当前工作目录中的文件。',IconFileText],['edit','编辑文件','修改授权范围内的项目文件。',IconCode],['bash','执行命令','运行开发、检查与验证命令。',IconTerminal2],['web','网页检索','检索公开网页并读取内容。',IconWorld]];
const extraCatalog=[['documentation','文档协作','Skill · 项目'],['browser','浏览器交互','Skill · 个人'],['extension','项目检查扩展','Extension · 项目']];
const emptyConfig=()=>({model:'inherit',thinking:'inherit',temperature:'',topP:'',maxTokens:'',instructions:'',output:'结论优先，说明完成的工作、验证结果和需要我决定的事项。',tools:['read','edit','bash'],extras:['documentation']});
const initialUrl=new URL(location.href);
const initialScope=Object.hasOwn(scopeNames,initialUrl.searchParams.get('scope'))?initialUrl.searchParams.get('scope'):'session';
function App(){
 const [scope,setScope]=useState(initialScope),[workflow,setWorkflow]=useState('direct'),[node,setNode]=useState('execute'),[tab,setTab]=useState('model'),[page,setPage]=useState('config'),[appearance,setAppearance]=useState(readAppearance),[inspector,setInspector]=useState(false),[allDrafts,setAllDrafts]=useState({}),[allSaved,setAllSaved]=useState({}),[notice,setNotice]=useState(''),[error,setError]=useState(''),[resourceOpen,setResourceOpen]=useState(false),[previewFailure,setPreviewFailure]=useState(false);
 const currentTheme = themeById(appearance.preset);
 useEffect(() => {
  applyAppearance(appearance);
  try { localStorage.setItem(appearanceStorageKey, JSON.stringify(appearance)); } catch { /* Keep usable without browser storage. */ }
  const url = new URL(location.href); url.searchParams.set('skin', appearance.preset); history.replaceState(null, '', url);
 }, [appearance]);
 const key=`${scope}:${workflow}:${node}`, draft=allDrafts[key]??emptyConfig(),saved=allSaved[key]??emptyConfig();
 const defaultModel=node==='remember'?'local':'sonnet';
 const effective=models.find(m=>m.id===(draft.model==='inherit'?defaultModel:draft.model));
 const effectiveThinking=draft.thinking==='inherit'?(effective.thinking.includes('medium')?'medium':effective.thinking[0]??'off'):draft.thinking;
 const baseSource=scope==='session'?'Nexus 默认配置':scope==='assistant'?'工作流默认配置':'工作流默认配置';
 const sequence=workflow==='direct'?['execute','remember']:['plan','review','execute','remember'];
 const changed=Object.keys(draft).filter(k=>JSON.stringify(draft[k])!==JSON.stringify(saved[k])).length;
 const info=nodes[node], NodeIcon=info.icon;
 function update(field,value){setAllDrafts(d=>({...d,[key]:{...draft,[field]:value}}));setNotice('');setError('');}
 function changeModel(value){setAllDrafts(d=>({...d,[key]:{...draft,model:value,thinking:'inherit'}}));setNotice('');setError('');}
 function selectNode(next){setNode(next);setPage('config');setError('');setNotice('');}
 function apply(){
  const max=Number(draft.maxTokens),temp=Number(draft.temperature),p=Number(draft.topP);
  if(!effective.temperature&&(draft.temperature!==''||draft.topP!=='')){setError('这个模型不支持已填写的采样参数。点击“恢复继承”清除后再应用。');setTab('model');return;}
  if(draft.maxTokens!==''&&(!Number.isInteger(max)||max<1||max>effective.limit)){setError(`输出预算需为 1–${effective.limit.toLocaleString()} 的整数。`);setTab('model');return;}
  if(draft.temperature!==''&&(temp<0||temp>2||!Number.isFinite(temp))){setError('Temperature 需要在 0–2 之间。');return;}
  if(draft.topP!==''&&(p<0||p>1||!Number.isFinite(p))){setError('Top-P 需要在 0–1 之间。');return;}
  if(previewFailure){setError('模拟保存失败。你的修改已保留，可以关闭“模拟失败”后重试。');return;}
  setAllSaved(s=>({...s,[key]:structuredClone(draft)}));setNotice(`已应用到${scopeNames[scope]}的预览 · 正式配置未更改`);setError('');
 }
 function changeScope(value){setScope(value);setNotice('');setError('');const url=new URL(location.href);url.searchParams.set('scope',value);history.replaceState(null,'',url);}
 const reset=()=>{setAllDrafts(d=>({...d,[key]:structuredClone(saved)}));setError('');setNotice('已撤销当前节点的未应用修改');};
 return <div className="preview-root">
  <header className="topbar"><div className="brand"><span className="brand-mark"><IconMessageCircle size={20}/></span><strong>Chat</strong><span className="crumb-slash">/</span><span>工作流配置</span></div><div className="top-actions"><span className="preview-label"><i/>交互预览<span className="desktop-only"> · 模拟数据</span></span><AppearancePicker value={appearance} onChange={setAppearance}/><ComponentLab theme={currentTheme} appearance={appearance} onAppearanceChange={setAppearance}/></div></header>
  <main className="page-shell">
   <div className="page-intro"><div><div className="eyebrow">WORKFLOW SETTINGS</div><h1>工作流配置</h1><p>为工作流中的每个执行者，安排合适的模型、指令和工具。</p></div><div className="context-picker"><span className="small-label">配置范围</span><select aria-label="配置范围" value={scope} onChange={e=>changeScope(e.target.value)}>{Object.entries(scopeNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><span className="context-caption">{scopeDescriptions[scope]}</span></div></div>
   <section className="workspace" aria-label="工作流配置编辑器">
    <aside className="workflow-sidebar"><div className="sidebar-top"><div className="small-label">工作流</div><div className="workflow-select"><IconGitBranch size={18}/><select aria-label="工作流" value={workflow} onChange={e=>{setWorkflow(e.target.value);selectNode(e.target.value==='direct'?'execute':'plan');}}><option value="direct">直接执行</option><option value="planning">规划执行</option></select></div><p>{workflow==='direct'?'直接处理请求，按需整理记忆。':'先规划与审核，再执行任务。'}</p></div><div className="node-heading">执行顺序 <span>{sequence.length} 个节点</span></div><nav aria-label="工作流节点" className="node-list">{sequence.map((id,index)=>{const item=nodes[id],I=item.icon;return <button key={id} className={`node-item ${node===id?'selected':''}`} onClick={()=>selectNode(id)} aria-current={node===id?'step':undefined}><span className="node-marker"><I size={18}/></span><span className="node-copy"><strong>{item.name}</strong><small>{id==='remember'?'按条件运行':id==='review'?'人工确认':'Agent 节点'}</small></span><span className="node-index">0{index+1}</span></button>;})}</nav><div className="sidebar-bottom"><IconInfoCircle size={17}/><div><strong>{scopeNames[scope]}配置</strong><p>{scope==='session'?'从下一次发送起，用于这段会话。':'用于之后按此默认配置启动的运行。'}</p><span>切换节点会保留草稿</span></div></div></aside>
    <div className="editor-column">
     {page==='shared'?<SharedModel model={effective} onBack={()=>setPage('config')}/>:<>
      <div className="node-header"><div key={node} className="node-avatar"><NodeIcon size={24}/></div><div className="node-title"><div><h2>{info.agent}</h2><span className="role-tag">{info.role}</span></div><p>{info.desc}</p></div><button className={`icon-button inspect-toggle ${inspector?'active':''}`} aria-label="查看有效配置" aria-pressed={inspector} onClick={()=>setInspector(!inspector)}><IconEye size={19}/></button></div>
      {node==='review'?<div className="review-content"><div className="review-illustration"><IconShieldCheck size={36} stroke={1.4}/></div><h3>把关键决定留给你</h3><p>规划完成后，工作流在这里暂停。你可以批准计划、补充信息，或要求重新规划。</p><div className="review-path"><span>规划完成</span><IconArrowRight size={16}/><span className="review-current">你的审核</span><IconArrowRight size={16}/><span>开始执行</span></div><div className="subtle-note"><IconInfoCircle size={17}/><span>这是人工审核节点，由工作流定义审核规则，无需配置模型。</span></div></div>:<>
      <div className="tabbar" role="tablist" aria-label="节点配置分类">{tabs.map(([id,label],i)=><button key={id} id={`tab-${id}`} role="tab" aria-selected={tab===id} aria-controls="node-panel" tabIndex={tab===id?0:-1} onClick={()=>setTab(id)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=tabs[(i+(e.key==='ArrowRight'?1:2))%3][0];setTab(next);document.getElementById(`tab-${next}`)?.focus();}}} className={tab===id?'active':''}>{label}</button>)}</div>
      <div key={`${scope}:${workflow}:${node}:${tab}`} className="editor-body" id="node-panel" role="tabpanel" aria-labelledby={`tab-${tab}`}>
       {tab==='model'&&<>
        <div className="section-heading"><h3>运行模型</h3><span className="source-label"><IconGitBranch size={13}/>{draft.model==='inherit'?`继承自${baseSource}`:`${scopeNames[scope]}已覆盖`}</span></div>
        <ModelPicker value={draft.model} effective={effective} defaultModel={models.find(m=>m.id===defaultModel)} onChange={changeModel}/>
        <div className="model-meta"><span><IconPhoto size={15}/>{effective.image?'支持图片输入':'仅文本输入'}</span><span><IconStack2 size={15}/>{effective.context} 上下文</span><button className="text-button" onClick={()=>setPage('shared')}>共享模型定义<IconArrowRight size={14}/></button></div>
        <div className="setting-row thinking-row"><div><label htmlFor="thinking">思考强度</label><p>为复杂问题分配更多推理时间。</p></div><select id="thinking" value={effective.thinking.length?draft.thinking:'off'} disabled={!effective.thinking.length} onChange={e=>update('thinking',e.target.value)}>{effective.thinking.length?<><option value="inherit">继承 · {effective.thinking.includes('medium')?'Medium':effective.thinking[0]}</option>{effective.thinking.map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</>:<option value="off">模型不支持</option>}</select></div>
        <div className="section-heading separated"><div><h3>生成参数</h3><p>微调这个执行者的回答方式。</p></div><button className="text-button muted" onClick={()=>{setAllDrafts(d=>({...d,[key]:{...draft,thinking:'inherit',temperature:'',topP:'',maxTokens:''}}));setError('');}}><IconRestore size={14}/>恢复继承</button></div>
        <div className="parameter-grid"><div className="parameter"><label htmlFor="temperature">Temperature <span>随机性</span></label><div className="number-wrap"><input id="temperature" type="number" inputMode="decimal" step="0.1" min="0" max="2" disabled={!effective.temperature} value={draft.temperature} placeholder={effective.temperature?'继承 · 0.7':'模型不支持调整'} onChange={e=>update('temperature',e.target.value)}/><span>0 — 2</span></div><p>{effective.temperature?'较低的值让回答更集中。':'该演示模型使用固定采样策略。'}</p></div><div className="parameter"><label htmlFor="top-p">Top-P <span>采样范围</span></label><div className="number-wrap"><input id="top-p" type="number" inputMode="decimal" step="0.05" min="0" max="1" disabled={!effective.temperature} value={draft.topP} placeholder={effective.temperature?'继承 · 1':'模型不支持调整'} onChange={e=>update('topP',e.target.value)}/><span>0 — 1</span></div><p>通常保留默认，按需单独调整。</p></div></div>
        <div className="setting-row output-row"><div><label htmlFor="max-tokens">单次输出预算</label><p>每次模型请求的输出限制，上限 {effective.limit.toLocaleString()} tokens。</p></div><div className="number-wrap budget"><input id="max-tokens" type="number" inputMode="numeric" min="1" max={effective.limit} value={draft.maxTokens} placeholder="继承 · 4,096" onChange={e=>update('maxTokens',e.target.value)}/><span>tokens</span></div></div>
        <button className="effective-summary" onClick={()=>setInspector(!inspector)} aria-expanded={inspector}><span className="summary-icon"><IconCircleCheck size={17}/></span><span><strong>下一次运行的配置</strong><small>{effective.name} · {effectiveThinking==='off'?'无思考配置':effectiveThinking+' 思考'} · {draft.maxTokens||'4,096'} tokens</small></span><IconChevronRight size={17}/></button>
       </>}
       {tab==='prompt'&&<><div className="section-heading"><h3>基础指令</h3><span className="source-label"><IconGitBranch size={13}/>来自工作流</span></div><div className="instruction-preview"><span className="small-label">{node==='remember'?'会话记忆维护职责':'执行职责'}</span><p>{node==='remember'?'只维护本会话中有依据的事实。先检查已有条目，避免重复；没有值得保留的信息时，无需写入。不重复回答用户。':'理解用户请求，在授权范围内完成工作。需要修改代码时先阅读项目规范；完成后说明结果、验证情况与尚未解决的问题。'}</p></div><div className="section-heading separated"><div><h3><label htmlFor="instructions">补充指令</label></h3><p>在基础指令之后追加，适用于{scopeNames[scope]}。</p></div><span className="optional">可选</span></div><textarea id="instructions" value={draft.instructions} onChange={e=>update('instructions',e.target.value)} placeholder="例如：优先用中文回复；涉及设计取舍时先解释原因。" rows={4}/><div className="section-heading separated"><h3><label htmlFor="output">输出要求</label></h3></div><textarea id="output" rows={2} value={draft.output} onChange={e=>update('output',e.target.value)}/><details className="advanced"><summary>高级：配置文件与来源</summary><p>正式接入后在这里查看主配置、追加文件和最终指令的装配来源。当前为交互样板。</p></details></>}
       {tab==='tools'&&<><div className="section-heading"><div><h3>可用工具</h3><p>{node==='remember'?'按维护职责提供必要工具。':'授予完成任务需要的能力。'}</p></div><span className="count-label">{node==='remember'?1:draft.tools.length} 项已启用</span></div><div className="resource-list">{(node==='remember'?[['memory','会话记忆','读取、写入和修订当前会话记忆。',IconNotes]]:toolCatalog).map(([id,name,desc,I])=><label className="resource-row" key={id}><span className="resource-icon"><I size={20}/></span><span className="resource-copy"><strong>{name}</strong><small>{desc}</small></span>{node==='remember'?<span className="required">节点必需</span>:<input className="switch" type="checkbox" role="switch" checked={draft.tools.includes(id)} onChange={e=>update('tools',e.target.checked?[...draft.tools,id]:draft.tools.filter(x=>x!==id))} aria-label={name}/>}</label>)}</div><div className="section-heading separated"><div><h3>指令资源与技能</h3><p>按需引用已维护的规则和工作方法。</p></div><Popover.Root open={resourceOpen} onOpenChange={setResourceOpen}><Popover.Trigger asChild><button className="text-button"><IconPlus size={16}/>添加</button></Popover.Trigger><Popover.Portal><Popover.Content className="resource-popover" align="end" sideOffset={8}><h4>添加到当前 Agent</h4>{extraCatalog.map(([id,name,kind])=><label key={id} className="resource-option"><input type="checkbox" checked={draft.extras.includes(id)} onChange={e=>update('extras',e.target.checked?[...draft.extras,id]:draft.extras.filter(x=>x!==id))}/><span>{name}<small>{kind}</small></span></label>)}<Popover.Close className="button secondary">完成</Popover.Close></Popover.Content></Popover.Portal></Popover.Root></div><div className="resource-list">{extraCatalog.filter(([id])=>draft.extras.includes(id)).map(([id,name,kind])=><div className="resource-row" key={id}><span className="resource-icon"><IconPuzzle size={20}/></span><span className="resource-copy"><strong>{name}</strong><small>{kind}</small></span><button className="icon-button" aria-label={`移除${name}`} onClick={()=>update('extras',draft.extras.filter(x=>x!==id))}><IconX size={16}/></button></div>)}{!draft.extras.length&&<p className="empty-state">还没有添加资源。点击“添加”选择。</p>}</div><details className="advanced"><summary>高级：扩展、插件与路径</summary><p>统一展示已选来源和加载结果；不在这页安装另一套运行环境。</p></details></>}
      </div></>}
      {inspector&&<div className="inspection"><div className="section-heading"><h3>有效配置 · 预览</h3><button className="icon-button" aria-label="关闭有效配置" onClick={()=>setInspector(false)}><IconX size={16}/></button></div><dl><dt>作用范围</dt><dd>{scopeNames[scope]}</dd><dt>当前节点</dt><dd>{info.agent}</dd>{node!=='review'&&<><dt>模型</dt><dd>{effective.name}<small>{draft.model==='inherit'?baseSource:scopeNames[scope]+'覆盖'}</small></dd><dt>输出预算</dt><dd>{draft.maxTokens||'4,096'} tokens<small>{draft.maxTokens?'当前配置':'继承默认值'}</small></dd></>}</dl><p>这里演示未来配置检查的展示方式。数据由样板提供，未读取正式运行配置。</p></div>}
      <footer className="editor-footer"><div className="save-state" aria-live="polite">{error?<span className="error"><IconInfoCircle size={16}/>{error}</span>:notice?<span className="success"><IconCheck size={16}/>{notice}</span>:<><span className={changed?'dirty-dot':'neutral-dot'}/><div><strong>{changed?`${changed} 项未应用修改`:JSON.stringify(draft)===JSON.stringify(emptyConfig())?'正在使用默认配置':'配置已应用'}</strong><small>{scope==='session'?'应用后从下一次发送起对本会话生效':'应用后对后续新受理的运行生效'}</small></div></>}</div>{node!=='review'&&<div className="footer-actions"><button className="button secondary" disabled={!changed} onClick={reset}>撤销修改</button><button className="button primary" disabled={!changed} onClick={apply}>{`应用到${scopeNames[scope]}`}<IconArrowRight size={16}/></button></div>}</footer>
     </>}
    </div>
   </section>
   <div className="preview-footnote"><span>设计样板 01 <span className="footnote-dot">·</span> 模型、能力与参数均为演示数据，应用仅影响当前预览。</span><label><input type="checkbox" checked={previewFailure} onChange={e=>setPreviewFailure(e.target.checked)}/>模拟保存失败</label></div>
  </main>
 </div>
}
function ModelPicker({value,effective,defaultModel,onChange}){const[open,setOpen]=useState(false);return <Popover.Root open={open} onOpenChange={setOpen}><Popover.Trigger asChild><button className="model-trigger" aria-label="选择运行模型"><span className="provider-avatar">{effective.letter}</span><span className="model-name"><strong>{effective.name}</strong><small>{effective.provider}<span>·</span>{value==='inherit'?'跟随默认模型':'已指定模型'}</small></span><span className="model-tag">{effective.tag}</span><IconChevronDown size={18}/></button></Popover.Trigger><Popover.Portal><Popover.Content className="model-popover" align="start" sideOffset={7}><Command label="选择模型"><div className="search-row"><IconSearch size={18}/><Command.Input placeholder="搜索模型或服务商…" autoFocus/></div><Command.List><Command.Empty>没有匹配的模型</Command.Empty><Command.Item value="继承 默认" onSelect={()=>{onChange('inherit');setOpen(false);}}><IconGitBranch size={19}/><span><strong>继承默认模型</strong><small>{defaultModel.name}</small></span>{value==='inherit'&&<IconCheck size={17}/>}</Command.Item><Command.Separator/>{models.map(m=><Command.Item key={m.id} value={`${m.name} ${m.provider}`} onSelect={()=>{onChange(m.id);setOpen(false);}}><span className="provider-avatar small">{m.letter}</span><span><strong>{m.name}</strong><small>{m.provider} · {m.image?'图片、文本':'文本'} · {m.context}</small></span>{value===m.id&&<IconCheck size={17}/>}</Command.Item>)}</Command.List><div className="picker-note">演示目录 · 仅用于体验配置交互</div></Command></Popover.Content></Popover.Portal></Popover.Root>}
function SharedModel({model,onBack}){return <div className="shared-page"><button className="text-button" onClick={onBack}><IconArrowLeft size={16}/>返回节点配置</button><div className="shared-title"><span className="provider-avatar">{model.letter}</span><div><div className="eyebrow">共享模型定义</div><h2>{model.name}</h2><p>{model.provider}</p></div></div><div className="scope-note"><IconWorld size={19}/><div><strong>所有使用此模型的 Agent 共用这份定义</strong><p>节点只选择模型和生成参数。模型能力、规格与连接在这里维护。</p></div></div><h3>模型能力与规格</h3><div className="spec-grid"><div><IconPhoto size={19}/><span>输入能力</span><strong>{model.image?'文本与图片':'仅文本'}</strong></div><div><IconStack2 size={19}/><span>上下文窗口</span><strong>{model.context} tokens</strong></div><div><IconBolt size={19}/><span>最大输出</span><strong>{model.limit.toLocaleString()} tokens</strong></div></div><div className="setting-row"><div><strong>服务商与连接</strong><p>API、认证、Headers 与兼容参数属于共享连接设置。</p></div><span className="role-tag">本次只读预览</span></div><div className="subtle-note"><IconInfoCircle size={18}/><span>这是范围与导航的演示。返回后，节点中的未应用修改会保留。</span></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
