/**
 * Trace事件严格联合与输入类型。判别字段eventName；未声明字段失败关闭。
 */
import { z } from "zod";
import {
  dshAdapterRequestCapturedSchema,
  bridgeDispatchPreparedSchema,
  httpCommandReceivedSchema,
  httpCommandAcceptedSchema,
  httpCommandRejectedSchema,
  httpCommandCompletedSchema,
  productTransactionStartedSchema,
  productTransactionCommittedSchema,
  productTransactionFailedSchema,
  productRunCreatedSchema,
  productRunTransitionedSchema,
  contextAssemblyStartedSchema,
  contextAssemblyCompletedSchema,
  contextAssemblyFailedSchema,
} from "./events-http.js";
import {
  memoryQueryStartedSchema,
  memoryQueryCompletedSchema,
  memoryQueryFailedSchema,
  memoryImportIntentCreatedSchema,
  memoryImportStartedSchema,
  memoryImportAcceptedSchema,
  memoryImportMaterializedSchema,
  memoryImportOutcomeUnknownSchema,
  memoryImportFailedSchema,
  memoryImportReconcileStartedSchema,
  memoryImportReconcileCompletedSchema,
  memoryImportReconcileFailedSchema,
} from "./events-memory.js";
import {
  workflowStartRequestedSchema,
  workflowStartStartedSchema,
  workflowStartFailedSchema,
  workflowStepStartedSchema,
  workflowStepCompletedSchema,
  workflowStepFailedSchema,
  workflowStepReplayedSchema,
  workflowMemoryNodeStartedSchema,
  workflowMemoryNodeCompletedSchema,
  workflowMemoryNodeFailedSchema,
  workflowMemoryNodeOutcomeUnknownSchema,
} from "./events-workflow.js";
import {
  planCandidateReceivedSchema,
  planCandidateRejectedSchema,
  planCandidatePublishedSchema,
  noteCandidateReceivedSchema,
  noteCandidateRejectedSchema,
  approvalCreatedSchema,
  decisionCommittedSchema,
  decisionRejectedSchema,
  workflowHookWaitingSchema,
  workflowHookResumeDispatchedSchema,
  workflowHookResumedSchema,
  workflowHookResumeFailedSchema,
} from "./events-decisions.js";
import {
  providerRequestStartedSchema,
  providerRequestCompletedSchema,
  providerRequestFailedSchema,
} from "./events-provider.js";
import {
  piNodeStartedSchema,
  piNodeCompletedSchema,
  piNodeFailedSchema,
  piOperationAcceptedSchema,
  piOperationStartedSchema,
  piOperationCompletedSchema,
  piOperationFailedSchema,
  piOperationOutcomeUnknownSchema,
  piSessionStartedSchema,
  piSessionSettledSchema,
  piTurnStartedSchema,
  piTurnCompletedSchema,
  piMessageCompletedSchema,
  piToolIntentPersistedSchema,
  piToolBlockedSchema,
  piToolCompletedSchema,
  piToolFailedSchema,
  piToolOutcomeUnknownSchema,
  piCompactionStartedSchema,
  piCompactionCompletedSchema,
} from "./events-pi.js";
import {
  executionValidatedSchema,
  executionRejectedSchema,
  productCommitStartedSchema,
  productCommitCommittedSchema,
  productCommitFailedSchema,
  serviceDebugStartedSchema,
  serviceDebugStoppedSchema,
} from "./events-commit.js";

export const traceEventSchema = z.discriminatedUnion("eventName", [
  dshAdapterRequestCapturedSchema,
  bridgeDispatchPreparedSchema,
  httpCommandReceivedSchema,
  httpCommandAcceptedSchema,
  httpCommandRejectedSchema,
  httpCommandCompletedSchema,
  productTransactionStartedSchema,
  productTransactionCommittedSchema,
  productTransactionFailedSchema,
  productRunCreatedSchema,
  productRunTransitionedSchema,
  contextAssemblyStartedSchema,
  contextAssemblyCompletedSchema,
  contextAssemblyFailedSchema,
  memoryQueryStartedSchema,
  memoryQueryCompletedSchema,
  memoryQueryFailedSchema,
  memoryImportIntentCreatedSchema,
  memoryImportStartedSchema,
  memoryImportAcceptedSchema,
  memoryImportMaterializedSchema,
  memoryImportOutcomeUnknownSchema,
  memoryImportFailedSchema,
  memoryImportReconcileStartedSchema,
  memoryImportReconcileCompletedSchema,
  memoryImportReconcileFailedSchema,
  workflowStartRequestedSchema,
  workflowStartStartedSchema,
  workflowStartFailedSchema,
  workflowStepStartedSchema,
  workflowStepCompletedSchema,
  workflowStepFailedSchema,
  workflowStepReplayedSchema,
  workflowMemoryNodeStartedSchema,
  workflowMemoryNodeCompletedSchema,
  workflowMemoryNodeFailedSchema,
  workflowMemoryNodeOutcomeUnknownSchema,
  planCandidateReceivedSchema,
  planCandidateRejectedSchema,
  planCandidatePublishedSchema,
  noteCandidateReceivedSchema,
  noteCandidateRejectedSchema,
  approvalCreatedSchema,
  decisionCommittedSchema,
  decisionRejectedSchema,
  workflowHookWaitingSchema,
  workflowHookResumeDispatchedSchema,
  workflowHookResumedSchema,
  workflowHookResumeFailedSchema,
  providerRequestStartedSchema,
  providerRequestCompletedSchema,
  providerRequestFailedSchema,
  piNodeStartedSchema,
  piNodeCompletedSchema,
  piNodeFailedSchema,
  piOperationAcceptedSchema,
  piOperationStartedSchema,
  piOperationCompletedSchema,
  piOperationFailedSchema,
  piOperationOutcomeUnknownSchema,
  piSessionStartedSchema,
  piSessionSettledSchema,
  piTurnStartedSchema,
  piTurnCompletedSchema,
  piMessageCompletedSchema,
  piToolIntentPersistedSchema,
  piToolBlockedSchema,
  piToolCompletedSchema,
  piToolFailedSchema,
  piToolOutcomeUnknownSchema,
  piCompactionStartedSchema,
  piCompactionCompletedSchema,
  executionValidatedSchema,
  executionRejectedSchema,
  productCommitStartedSchema,
  productCommitCommittedSchema,
  productCommitFailedSchema,
  serviceDebugStartedSchema,
  serviceDebugStoppedSchema,
]);

export type TraceEvent = z.infer<typeof traceEventSchema>;

type DistributiveOmit<T, K extends PropertyKey> = T extends unknown ? Omit<T, K> : never;

/**
 * 待写入的Trace事件。schemaVersion/eventId/timestamp由Sink生成。
 * 不存在任意内容通道：每个事件只允许自己声明的字段。
 */
export type TraceEventInput = DistributiveOmit<
  TraceEvent,
  "schemaVersion" | "eventId" | "timestamp"
>;
