import { z } from "zod";
import {
  approvalRequestSchema,
  artifactSchema,
  commandReceiptSchema,
  contextPackageSchema,
  decisionSchema,
  executionCandidateSchema,
  executionContractSchema,
  memoryAdoptionSchema,
  memoryImportIntentSchema,
  memoryImportResultSchema,
  memoryQuerySchema,
  memoryResultSnapshotSchema,
  messageSchema,
  outboxEntrySchema,
  planRevisionSchema,
  productRunV1Schema,
  productSessionSchema,
  projectActionSchema,
  projectCandidateSchema,
  projectContributionSchema,
  projectMilestoneSchema,
  projectObservationSchema,
  projectParticipantSchema,
  projectResourceSchema,
  projectSchema,
  projectStageSchema,
  projectStateTransitionSchema,
  projectUpdateSchema,
  revisionInputSchema,
  runAttemptSchema,
  runContextRequestSchema,
  validationResultSchema,
} from "@chat/contracts";
import {
  projectDecisionV19Schema as projectDecisionSchema,
  projectEvidenceV19Schema as projectEvidenceSchema,
  projectMethodSnapshotV19Schema as projectMethodSnapshotSchema,
  projectWorkV19Schema as projectWorkSchema,
} from "./legacy-v19.js";

/** S1迁移前的精确v5读取合同；只用于向前迁移，不作为当前写Schema。 */
export const productSnapshotV5Schema = z
  .object({
    schemaVersion: z.literal("chat-product-store.v5"),
    storeRevision: z.number().int().nonnegative(),
    committedAt: z.iso.datetime(),
    entities: z
      .object({
        sessions: z.record(z.string(), productSessionSchema),
        messages: z.record(z.string(), messageSchema),
        runs: z.record(z.string(), productRunV1Schema),
        attempts: z.record(z.string(), runAttemptSchema),
        plans: z.record(z.string(), planRevisionSchema),
        revisionInputs: z.record(z.string(), revisionInputSchema),
        approvalRequests: z.record(z.string(), approvalRequestSchema),
        decisions: z.record(z.string(), decisionSchema),
        executionContracts: z.record(z.string(), executionContractSchema),
        executionCandidates: z.record(z.string(), executionCandidateSchema),
        validationResults: z.record(z.string(), validationResultSchema),
        artifacts: z.record(z.string(), artifactSchema),
        contextRequests: z.record(z.string(), runContextRequestSchema),
        memoryQueries: z.record(z.string(), memoryQuerySchema),
        memoryResultSnapshots: z.record(z.string(), memoryResultSnapshotSchema),
        memoryAdoptions: z.record(z.string(), memoryAdoptionSchema),
        contextPackages: z.record(z.string(), contextPackageSchema),
        memoryImportIntents: z.record(z.string(), memoryImportIntentSchema),
        memoryImportResults: z.record(z.string(), memoryImportResultSchema),
        projects: z.record(z.string(), projectSchema),
        projectMethodSnapshots: z.record(z.string(), projectMethodSnapshotSchema),
        projectStages: z.record(z.string(), projectStageSchema),
        projectMilestones: z.record(z.string(), projectMilestoneSchema),
        projectUpdates: z.record(z.string(), projectUpdateSchema),
        projectStateTransitions: z.record(z.string(), projectStateTransitionSchema),
        projectResources: z.record(z.string(), projectResourceSchema),
        projectParticipants: z.record(z.string(), projectParticipantSchema),
        projectWorks: z.record(z.string(), projectWorkSchema),
        projectActions: z.record(z.string(), projectActionSchema),
        projectContributions: z.record(z.string(), projectContributionSchema),
        projectEvidence: z.record(z.string(), projectEvidenceSchema),
        projectDecisions: z.record(z.string(), projectDecisionSchema),
        projectObservations: z.record(z.string(), projectObservationSchema),
        projectCandidates: z.record(z.string(), projectCandidateSchema),
      })
      .strict(),
    commandReceipts: z.record(z.string(), commandReceiptSchema),
    outbox: z.record(z.string(), outboxEntrySchema),
  })
  .strict();

export type ProductSnapshotV5 = z.infer<typeof productSnapshotV5Schema>;
