"""add execution governance schema

Revision ID: 344961dfd573
Revises: 36a6de371c70
Create Date: 2026-07-22 21:16:23.347050
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "344961dfd573"
down_revision: Union[str, Sequence[str], None] = "36a6de371c70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authorization_consumptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("grant_id", sa.String(length=36), nullable=False),
        sa.Column("consumption_no", sa.Integer(), nullable=False),
        sa.Column("consumer_kind", sa.String(length=50), nullable=False),
        sa.Column("consumer_id", sa.String(length=120), nullable=False),
        sa.Column("attempt_id", sa.String(length=100), nullable=True),
        sa.Column("idempotency_key", sa.String(length=180), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("claimed_by", sa.String(length=120), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["grant_id"], ["authorization_grants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("grant_id", "consumption_no"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_authorization_consumptions_grant_id"),
        "authorization_consumptions",
        ["grant_id"],
        unique=False,
    )
    op.create_table(
        "authorization_grants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("decision_record_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("grant_kind", sa.String(length=40), nullable=False),
        sa.Column("binding_hash", sa.String(length=64), nullable=False),
        sa.Column("constraints_json", sa.JSON(), nullable=False),
        sa.Column("max_consumptions", sa.Integer(), nullable=False),
        sa.Column("consumed_count", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidation_reason", sa.String(length=120), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["decision_record_id"], ["decision_records.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["subject_id"], ["decision_subjects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("decision_record_id"),
    )
    op.create_index(
        "ix_authorization_grant_status_expiry", "authorization_grants", ["status", "expires_at"], unique=False
    )
    op.create_table(
        "decision_point_definitions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("subject_kind", sa.String(length=80), nullable=False),
        sa.Column("default_mode", sa.String(length=32), nullable=False),
        sa.Column("allowed_human_actions_json", sa.JSON(), nullable=False),
        sa.Column("applicability_schema_json", sa.JSON(), nullable=False),
        sa.Column("response_schema_json", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("definition_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", "version"),
    )
    op.create_table(
        "decision_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("policy_evaluation_id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=True),
        sa.Column("request_item_id", sa.String(length=36), nullable=True),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("actor_principal_id", sa.String(length=100), nullable=False),
        sa.Column("decision_code", sa.String(length=40), nullable=False),
        sa.Column("authorization_effect", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("bound_subject_hash", sa.String(length=64), nullable=False),
        sa.Column("policy_rule_refs_json", sa.JSON(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("record_hash", sa.String(length=64), nullable=False),
        sa.Column("revokes_record_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["policy_evaluation_id"], ["policy_evaluations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["request_id"], ["human_decision_requests.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["request_item_id"], ["human_decision_request_items.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["revokes_record_id"], ["decision_records.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["subject_id"], ["decision_subjects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("record_hash"),
    )
    op.create_table(
        "decision_subjects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("subject_kind", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=100), nullable=False),
        sa.Column("resource_revision", sa.String(length=100), nullable=False),
        sa.Column("subject_hash", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("interaction_id", sa.String(length=36), nullable=True),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("run_attempt_id", sa.String(length=36), nullable=True),
        sa.Column("workflow_definition_id", sa.String(length=100), nullable=True),
        sa.Column("workflow_version", sa.String(length=40), nullable=True),
        sa.Column("node_id", sa.String(length=120), nullable=True),
        sa.Column("decision_view_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["interaction_id"], ["interactions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_attempt_id"], ["run_attempts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["product_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["session_id"], ["product_sessions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_kind", "resource_id", "resource_revision", "subject_hash"),
    )
    op.create_index(
        op.f("ix_decision_subjects_session_id"), "decision_subjects", ["session_id"], unique=False
    )
    op.create_table(
        "execution_draft_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("draft_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("previous_revision_id", sa.String(length=36), nullable=True),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("schema_version", sa.String(length=40), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("execution_brief_text", sa.Text(), nullable=False),
        sa.Column("context_hash", sa.String(length=64), nullable=False),
        sa.Column("draft_hash", sa.String(length=64), nullable=False),
        sa.Column("author_type", sa.String(length=32), nullable=False),
        sa.Column("author_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["draft_id"], ["execution_drafts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["previous_revision_id"], ["execution_draft_revisions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["subject_id"], ["decision_subjects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("draft_id", "revision"),
        sa.UniqueConstraint("subject_id"),
    )
    op.create_index(
        op.f("ix_execution_draft_revisions_draft_hash"),
        "execution_draft_revisions",
        ["draft_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_draft_revisions_draft_id"), "execution_draft_revisions", ["draft_id"], unique=False
    )
    op.create_table(
        "execution_drafts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("interaction_id", sa.String(length=36), nullable=False),
        sa.Column("principal_id", sa.String(length=100), nullable=False),
        sa.Column("workflow_definition_id", sa.String(length=100), nullable=False),
        sa.Column("workflow_version", sa.String(length=40), nullable=False),
        sa.Column("branch_key", sa.String(length=80), nullable=False),
        sa.Column("current_revision_id", sa.String(length=36), nullable=True),
        sa.Column("accepted_revision_id", sa.String(length=36), nullable=True),
        sa.Column("acceptance_decision_record_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["acceptance_decision_record_id"], ["decision_records.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["accepted_revision_id"], ["execution_draft_revisions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["current_revision_id"], ["execution_draft_revisions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["interaction_id"], ["interactions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["session_id"], ["product_sessions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("interaction_id", "workflow_definition_id", "branch_key"),
    )
    op.create_index(
        op.f("ix_execution_drafts_interaction_id"), "execution_drafts", ["interaction_id"], unique=False
    )
    op.create_index(op.f("ix_execution_drafts_session_id"), "execution_drafts", ["session_id"], unique=False)
    op.create_index(op.f("ix_execution_drafts_status"), "execution_drafts", ["status"], unique=False)
    op.create_table(
        "governance_outbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("aggregate_kind", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.String(length=100), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=180), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("locked_by", sa.String(length=120), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    op.create_index(
        "ix_governance_outbox_status_available", "governance_outbox", ["status", "available_at"], unique=False
    )
    op.create_table(
        "hitl_policy_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("policy_set_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("base_revision_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=40), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column("change_summary", sa.Text(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("activated_by", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["base_revision_id"], ["hitl_policy_revisions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["policy_set_id"], ["hitl_policy_sets.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("policy_set_id", "revision"),
    )
    op.create_index(
        op.f("ix_hitl_policy_revisions_policy_set_id"),
        "hitl_policy_revisions",
        ["policy_set_id"],
        unique=False,
    )
    op.create_table(
        "hitl_policy_sets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("authority", sa.String(length=40), nullable=False),
        sa.Column("scope_kind", sa.String(length=40), nullable=False),
        sa.Column("scope_ref_id", sa.String(length=120), nullable=False),
        sa.Column("scope_ref_revision", sa.String(length=80), nullable=False),
        sa.Column("owner_principal_id", sa.String(length=100), nullable=False),
        sa.Column("active_revision_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["active_revision_id"], ["hitl_policy_revisions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "authority", "scope_kind", "scope_ref_id", "scope_ref_revision", "owner_principal_id"
        ),
    )
    op.create_index(
        "ix_hitl_policy_scope", "hitl_policy_sets", ["scope_kind", "scope_ref_id", "status"], unique=False
    )
    op.create_table(
        "hitl_policy_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("principal_id", sa.String(length=100), nullable=False),
        sa.Column("resolver_version", sa.String(length=40), nullable=False),
        sa.Column("active_revision_refs_json", sa.JSON(), nullable=False),
        sa.Column("preference_rules_json", sa.JSON(), nullable=False),
        sa.Column("floor_rules_json", sa.JSON(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_hash"),
    )
    op.create_index(
        op.f("ix_hitl_policy_snapshots_principal_id"), "hitl_policy_snapshots", ["principal_id"], unique=False
    )
    op.create_table(
        "human_decision_request_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("policy_evaluation_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("item_key", sa.String(length=160), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("allowed_actions_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("decision_record_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["decision_record_id"], ["decision_records.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["policy_evaluation_id"], ["policy_evaluations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["request_id"], ["human_decision_requests.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["subject_id"], ["decision_subjects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id", "item_key"),
    )
    op.create_index(
        op.f("ix_human_decision_request_items_request_id"),
        "human_decision_request_items",
        ["request_id"],
        unique=False,
    )
    op.create_table(
        "human_decision_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("decision_point_key", sa.String(length=80), nullable=False),
        sa.Column("principal_id", sa.String(length=100), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("interaction_id", sa.String(length=36), nullable=True),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("reason_summary", sa.Text(), nullable=False),
        sa.Column("visible_evidence_json", sa.JSON(), nullable=False),
        sa.Column("consequence_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_by_request_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["interaction_id"], ["interactions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["product_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["session_id"], ["product_sessions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["superseded_by_request_id"], ["human_decision_requests.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_human_request_principal_status",
        "human_decision_requests",
        ["principal_id", "status", "expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_human_request_run_status",
        "human_decision_requests",
        ["run_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "model_call_draft_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("model_call_draft_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("previous_revision_id", sa.String(length=36), nullable=True),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("provider_id", sa.String(length=100), nullable=False),
        sa.Column("provider_protocol", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("provider_request_json", sa.JSON(), nullable=False),
        sa.Column("provider_body", sa.LargeBinary(), nullable=True),
        sa.Column("provider_body_sha256", sa.String(length=64), nullable=False),
        sa.Column("binding_hash", sa.String(length=64), nullable=False),
        sa.Column("effective_context_json", sa.JSON(), nullable=False),
        sa.Column("context_source_annotations_json", sa.JSON(), nullable=False),
        sa.Column("adapter_version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["model_call_draft_id"], ["model_call_drafts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["previous_revision_id"], ["model_call_draft_revisions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["subject_id"], ["decision_subjects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_call_draft_id", "revision"),
        sa.UniqueConstraint("subject_id"),
    )
    op.create_index(
        op.f("ix_model_call_draft_revisions_model_call_draft_id"),
        "model_call_draft_revisions",
        ["model_call_draft_id"],
        unique=False,
    )
    op.create_table(
        "model_call_drafts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("run_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("workflow_node_id", sa.String(length=120), nullable=False),
        sa.Column("call_ordinal", sa.Integer(), nullable=False),
        sa.Column("current_revision_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["current_revision_id"], ["model_call_draft_revisions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["run_attempt_id"], ["run_attempts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["product_runs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "workflow_node_id", "call_ordinal"),
    )
    op.create_index(
        "ix_model_call_slot",
        "model_call_drafts",
        ["run_id", "workflow_node_id", "call_ordinal"],
        unique=False,
    )
    op.create_table(
        "policy_evaluations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("decision_point_definition_id", sa.String(length=36), nullable=False),
        sa.Column("policy_snapshot_id", sa.String(length=36), nullable=True),
        sa.Column("principal_id", sa.String(length=100), nullable=False),
        sa.Column("applicability_status", sa.String(length=32), nullable=False),
        sa.Column("facts_json", sa.JSON(), nullable=False),
        sa.Column("facts_hash", sa.String(length=64), nullable=False),
        sa.Column("matched_rule_refs_json", sa.JSON(), nullable=False),
        sa.Column("floor_action", sa.String(length=32), nullable=False),
        sa.Column("preference_action", sa.String(length=32), nullable=False),
        sa.Column("final_action", sa.String(length=32), nullable=True),
        sa.Column("result_status", sa.String(length=32), nullable=False),
        sa.Column("reason_codes_json", sa.JSON(), nullable=False),
        sa.Column("resolver_version", sa.String(length=40), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_point_definition_id"], ["decision_point_definitions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["policy_snapshot_id"], ["hitl_policy_snapshots.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["subject_id"], ["decision_subjects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_policy_eval_subject_point",
        "policy_evaluations",
        ["subject_id", "decision_point_definition_id", "evaluated_at"],
        unique=False,
    )
    op.create_table(
        "run_specs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("draft_revision_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("policy_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("schema_version", sa.String(length=40), nullable=False),
        sa.Column("compiler_version", sa.String(length=40), nullable=False),
        sa.Column("spec_json", sa.JSON(), nullable=False),
        sa.Column("run_spec_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("bound_run_id", sa.String(length=36), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason_code", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["bound_run_id"], ["product_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["draft_revision_id"], ["execution_draft_revisions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["policy_snapshot_id"], ["hitl_policy_snapshots.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["subject_id"], ["decision_subjects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bound_run_id"),
        sa.UniqueConstraint("draft_revision_id", "compiler_version", "run_spec_hash"),
        sa.UniqueConstraint("subject_id"),
    )
    op.create_index(op.f("ix_run_specs_draft_revision_id"), "run_specs", ["draft_revision_id"], unique=False)
    op.create_index(op.f("ix_run_specs_run_spec_hash"), "run_specs", ["run_spec_hash"], unique=False)
    op.create_table(
        "hitl_policy_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("policy_revision_id", sa.String(length=36), nullable=False),
        sa.Column("decision_point_key", sa.String(length=80), nullable=False),
        sa.Column("definition_version", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("condition_json", sa.JSON(), nullable=True),
        sa.Column("on_match", sa.String(length=32), nullable=True),
        sa.Column("constraints_json", sa.JSON(), nullable=False),
        sa.Column("reason_template", sa.Text(), nullable=False),
        sa.Column("condition_specificity", sa.Integer(), nullable=False),
        sa.Column("rule_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["policy_revision_id"], ["hitl_policy_revisions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("policy_revision_id", "decision_point_key"),
    )
    op.create_index(
        op.f("ix_hitl_policy_rules_policy_revision_id"),
        "hitl_policy_rules",
        ["policy_revision_id"],
        unique=False,
    )
    op.create_table(
        "model_call_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("model_call_draft_revision_id", sa.String(length=36), nullable=False),
        sa.Column("authorization_consumption_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("run_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("transport_idempotency_key", sa.String(length=180), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("provider_response_id", sa.String(length=180), nullable=True),
        sa.Column("usage_json", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_byte_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["authorization_consumption_id"], ["authorization_consumptions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["model_call_draft_revision_id"], ["model_call_draft_revisions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["run_attempt_id"], ["run_attempts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["product_runs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("authorization_consumption_id"),
        sa.UniqueConstraint("model_call_draft_revision_id", "attempt_number"),
        sa.UniqueConstraint("transport_idempotency_key"),
    )
    op.create_table(
        "runtime_interrupt_links",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("decision_request_id", sa.String(length=36), nullable=False),
        sa.Column("product_run_id", sa.String(length=36), nullable=False),
        sa.Column("run_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("maf_workflow_name", sa.String(length=120), nullable=False),
        sa.Column("maf_graph_signature_hash", sa.String(length=64), nullable=False),
        sa.Column("maf_checkpoint_id", sa.String(length=160), nullable=False),
        sa.Column("maf_request_id", sa.String(length=160), nullable=False),
        sa.Column("maf_executor_id", sa.String(length=120), nullable=False),
        sa.Column("agui_thread_id", sa.String(length=120), nullable=False),
        sa.Column("agui_run_id", sa.String(length=120), nullable=False),
        sa.Column("agui_interrupt_id", sa.String(length=160), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_projected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resume_attempts", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["decision_request_id"], ["human_decision_requests.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_run_id"], ["product_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_attempt_id"], ["run_attempts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("decision_request_id"),
        sa.UniqueConstraint("maf_checkpoint_id", "maf_request_id"),
    )
    op.create_index(
        "ix_runtime_interrupt_run_status",
        "runtime_interrupt_links",
        ["product_run_id", "status"],
        unique=False,
    )
    op.create_table(
        "tool_call_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("run_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("workflow_node_id", sa.String(length=120), nullable=False),
        sa.Column("provider_tool_call_id", sa.String(length=180), nullable=False),
        sa.Column("tool_id", sa.String(length=100), nullable=False),
        sa.Column("tool_definition_revision", sa.String(length=80), nullable=False),
        sa.Column("arguments_json", sa.JSON(), nullable=False),
        sa.Column("arguments_hash", sa.String(length=64), nullable=False),
        sa.Column("target_summary", sa.Text(), nullable=False),
        sa.Column("risk_snapshot_json", sa.JSON(), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_attempt_id"], ["run_attempts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["product_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["subject_id"], ["decision_subjects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "provider_tool_call_id"),
        sa.UniqueConstraint("subject_id"),
    )
    op.create_index(op.f("ix_tool_call_requests_run_id"), "tool_call_requests", ["run_id"], unique=False)
    op.create_table(
        "turn_summaries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("interaction_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("topic", sa.String(length=240), nullable=False),
        sa.Column("summary_json", sa.JSON(), nullable=False),
        sa.Column("project_hint", sa.String(length=240), nullable=True),
        sa.Column("extraction_status", sa.String(length=32), nullable=False),
        sa.Column("source_model_call_revision_id", sa.String(length=36), nullable=True),
        sa.Column("summary_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["interaction_id"], ["interactions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["product_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["session_id"], ["product_sessions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["source_model_call_revision_id"], ["model_call_draft_revisions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("interaction_id"),
    )
    op.create_index(
        "ix_turn_summaries_session_created", "turn_summaries", ["session_id", "created_at"], unique=False
    )
    with op.batch_alter_table("product_messages") as batch_op:
        batch_op.add_column(sa.Column("commit_decision_record_id", sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            "fk_product_messages_commit_decision",
            "decision_records",
            ["commit_decision_record_id"],
            ["id"],
            ondelete="RESTRICT",
        )
    with op.batch_alter_table("product_runs") as batch_op:
        batch_op.add_column(sa.Column("execution_draft_revision_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("run_spec_id", sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            "fk_product_runs_run_spec", "run_specs", ["run_spec_id"], ["id"], ondelete="RESTRICT"
        )
        batch_op.create_foreign_key(
            "fk_product_runs_execution_draft_revision",
            "execution_draft_revisions",
            ["execution_draft_revision_id"],
            ["id"],
            ondelete="RESTRICT",
        )
    with op.batch_alter_table("run_attempts") as batch_op:
        batch_op.add_column(
            sa.Column("start_authorization_consumption_id", sa.String(length=36), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_run_attempts_start_authorization",
            "authorization_consumptions",
            ["start_authorization_consumption_id"],
            ["id"],
            ondelete="RESTRICT",
        )
    with op.batch_alter_table("tool_executions") as batch_op:
        batch_op.add_column(sa.Column("tool_call_request_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("authorization_consumption_id", sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            "fk_tool_executions_authorization",
            "authorization_consumptions",
            ["authorization_consumption_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            "fk_tool_executions_request",
            "tool_call_requests",
            ["tool_call_request_id"],
            ["id"],
            ondelete="RESTRICT",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tool_executions") as batch_op:
        batch_op.drop_constraint("fk_tool_executions_request", type_="foreignkey")
        batch_op.drop_constraint("fk_tool_executions_authorization", type_="foreignkey")
        batch_op.drop_column("authorization_consumption_id")
        batch_op.drop_column("tool_call_request_id")
    with op.batch_alter_table("run_attempts") as batch_op:
        batch_op.drop_constraint("fk_run_attempts_start_authorization", type_="foreignkey")
        batch_op.drop_column("start_authorization_consumption_id")
    with op.batch_alter_table("product_runs") as batch_op:
        batch_op.drop_constraint("fk_product_runs_run_spec", type_="foreignkey")
        batch_op.drop_constraint("fk_product_runs_execution_draft_revision", type_="foreignkey")
        batch_op.drop_column("run_spec_id")
        batch_op.drop_column("execution_draft_revision_id")
    with op.batch_alter_table("product_messages") as batch_op:
        batch_op.drop_constraint("fk_product_messages_commit_decision", type_="foreignkey")
        batch_op.drop_column("commit_decision_record_id")
    op.drop_index("ix_turn_summaries_session_created", table_name="turn_summaries")
    op.drop_table("turn_summaries")
    op.drop_index(op.f("ix_tool_call_requests_run_id"), table_name="tool_call_requests")
    op.drop_table("tool_call_requests")
    op.drop_index("ix_runtime_interrupt_run_status", table_name="runtime_interrupt_links")
    op.drop_table("runtime_interrupt_links")
    op.drop_table("model_call_attempts")
    op.drop_index(op.f("ix_hitl_policy_rules_policy_revision_id"), table_name="hitl_policy_rules")
    op.drop_table("hitl_policy_rules")
    op.drop_index(op.f("ix_run_specs_run_spec_hash"), table_name="run_specs")
    op.drop_index(op.f("ix_run_specs_draft_revision_id"), table_name="run_specs")
    op.drop_table("run_specs")
    op.drop_index("ix_policy_eval_subject_point", table_name="policy_evaluations")
    op.drop_table("policy_evaluations")
    op.drop_index("ix_model_call_slot", table_name="model_call_drafts")
    op.drop_table("model_call_drafts")
    op.drop_index(
        op.f("ix_model_call_draft_revisions_model_call_draft_id"), table_name="model_call_draft_revisions"
    )
    op.drop_table("model_call_draft_revisions")
    op.drop_index("ix_human_request_run_status", table_name="human_decision_requests")
    op.drop_index("ix_human_request_principal_status", table_name="human_decision_requests")
    op.drop_table("human_decision_requests")
    op.drop_index(
        op.f("ix_human_decision_request_items_request_id"), table_name="human_decision_request_items"
    )
    op.drop_table("human_decision_request_items")
    op.drop_index(op.f("ix_hitl_policy_snapshots_principal_id"), table_name="hitl_policy_snapshots")
    op.drop_table("hitl_policy_snapshots")
    op.drop_index("ix_hitl_policy_scope", table_name="hitl_policy_sets")
    op.drop_table("hitl_policy_sets")
    op.drop_index(op.f("ix_hitl_policy_revisions_policy_set_id"), table_name="hitl_policy_revisions")
    op.drop_table("hitl_policy_revisions")
    op.drop_index("ix_governance_outbox_status_available", table_name="governance_outbox")
    op.drop_table("governance_outbox")
    op.drop_index(op.f("ix_execution_drafts_status"), table_name="execution_drafts")
    op.drop_index(op.f("ix_execution_drafts_session_id"), table_name="execution_drafts")
    op.drop_index(op.f("ix_execution_drafts_interaction_id"), table_name="execution_drafts")
    op.drop_table("execution_drafts")
    op.drop_index(op.f("ix_execution_draft_revisions_draft_id"), table_name="execution_draft_revisions")
    op.drop_index(op.f("ix_execution_draft_revisions_draft_hash"), table_name="execution_draft_revisions")
    op.drop_table("execution_draft_revisions")
    op.drop_index(op.f("ix_decision_subjects_session_id"), table_name="decision_subjects")
    op.drop_table("decision_subjects")
    op.drop_table("decision_records")
    op.drop_table("decision_point_definitions")
    op.drop_index("ix_authorization_grant_status_expiry", table_name="authorization_grants")
    op.drop_table("authorization_grants")
    op.drop_index(op.f("ix_authorization_consumptions_grant_id"), table_name="authorization_consumptions")
    op.drop_table("authorization_consumptions")
    # ### end Alembic commands ###
