"""create product session store

Revision ID: 8c84fc794c2b
Revises:
Create Date: 2026-07-21
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8c84fc794c2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('active_run_id', sa.String(length=36), nullable=True),
    sa.Column('model_provider_id', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_sessions_scope_id'), 'product_sessions', ['scope_id'], unique=False)
    op.create_index(op.f('ix_product_sessions_status'), 'product_sessions', ['status'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_message_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['product_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_session_id'), 'interactions', ['session_id'], unique=False)
    op.create_table('product_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('interaction_id', sa.String(length=36), nullable=False),
    sa.Column('initial_agui_run_id', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_user_message_id', sa.String(length=36), nullable=False),
    sa.Column('assistant_message_id', sa.String(length=36), nullable=True),
    sa.Column('model_provider_id', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('draft_id', sa.String(length=100), nullable=True),
    sa.Column('approval_id', sa.String(length=100), nullable=True),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['product_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'initial_agui_run_id')
    )
    op.create_index(op.f('ix_product_runs_interaction_id'), 'product_runs', ['interaction_id'], unique=False)
    op.create_index(op.f('ix_product_runs_session_id'), 'product_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_product_runs_status'), 'product_runs', ['status'], unique=False)
    op.create_table('product_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('interaction_id', sa.String(length=36), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('agui_message_id', sa.String(length=100), nullable=False),
    sa.Column('parent_message_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('context_eligible', sa.Boolean(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['product_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['product_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'agui_message_id'),
    sa.UniqueConstraint('session_id', 'ordinal')
    )
    op.create_index('ix_product_messages_context', 'product_messages', ['session_id', 'context_eligible', 'ordinal'], unique=False)
    op.create_index(op.f('ix_product_messages_session_id'), 'product_messages', ['session_id'], unique=False)
    op.create_table('run_protocol_ids',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('product_run_id', sa.String(length=36), nullable=False),
    sa.Column('agui_run_id', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_run_id'], ['product_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['product_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'agui_run_id')
    )
    op.create_index(op.f('ix_run_protocol_ids_product_run_id'), 'run_protocol_ids', ['product_run_id'], unique=False)
    op.create_index(op.f('ix_run_protocol_ids_session_id'), 'run_protocol_ids', ['session_id'], unique=False)
    op.create_table('trace_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['product_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['product_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sequence')
    )
    op.create_index(op.f('ix_trace_events_run_id'), 'trace_events', ['run_id'], unique=False)
    op.create_index(op.f('ix_trace_events_session_id'), 'trace_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trace_events_session_id'), table_name='trace_events')
    op.drop_index(op.f('ix_trace_events_run_id'), table_name='trace_events')
    op.drop_table('trace_events')
    op.drop_index(op.f('ix_run_protocol_ids_session_id'), table_name='run_protocol_ids')
    op.drop_index(op.f('ix_run_protocol_ids_product_run_id'), table_name='run_protocol_ids')
    op.drop_table('run_protocol_ids')
    op.drop_index(op.f('ix_product_messages_session_id'), table_name='product_messages')
    op.drop_index('ix_product_messages_context', table_name='product_messages')
    op.drop_table('product_messages')
    op.drop_index(op.f('ix_product_runs_status'), table_name='product_runs')
    op.drop_index(op.f('ix_product_runs_session_id'), table_name='product_runs')
    op.drop_index(op.f('ix_product_runs_interaction_id'), table_name='product_runs')
    op.drop_table('product_runs')
    op.drop_index(op.f('ix_interactions_session_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_product_sessions_status'), table_name='product_sessions')
    op.drop_index(op.f('ix_product_sessions_scope_id'), table_name='product_sessions')
    op.drop_table('product_sessions')
    # ### end Alembic commands ###
