"""add evidence artifact provenance validation schema

Revision ID: ddc1d173586e
Revises: f01d3a7c9e25
Create Date: 2026-07-26 00:21:30.501130
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ddc1d173586e'
down_revision: Union[str, Sequence[str], None] = 'f01d3a7c9e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_blobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('integrity_status', sa.String(length=20), nullable=False),
    sa.Column('gc_status', sa.String(length=24), nullable=False),
    sa.Column('orphaned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_gc_error_code', sa.String(length=100), nullable=True),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("gc_status IN ('active','orphan_candidate','deleting','delete_failed')", name='ck_artifact_blob_gc_status'),
    sa.CheckConstraint("integrity_status IN ('available','missing','corrupt')", name='ck_artifact_blob_integrity_status'),
    sa.CheckConstraint('row_version >= 1', name='ck_artifact_blob_row_version'),
    sa.CheckConstraint('size_bytes >= 0', name='ck_artifact_blob_size'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_id', 'sha256', name='uq_artifact_blobs_scope_sha256'),
    sa.UniqueConstraint('storage_path', name='uq_artifact_blobs_storage_path')
    )
    op.create_index('ix_artifact_blobs_scope_created', 'artifact_blobs', ['scope_id', 'created_at'], unique=False)
    op.create_index('ix_artifact_blobs_scope_gc', 'artifact_blobs', ['scope_id', 'gc_status'], unique=False)
    op.create_index(op.f('ix_artifact_blobs_scope_id'), 'artifact_blobs', ['scope_id'], unique=False)
    op.create_table('validation_capabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=False),
    sa.Column('capability_key', sa.String(length=80), nullable=False),
    sa.Column('capability_version', sa.String(length=40), nullable=False),
    sa.Column('capability_hash', sa.String(length=64), nullable=False),
    sa.Column('executable_policy', sa.String(length=40), nullable=False),
    sa.Column('executable_ref', sa.String(length=100), nullable=False),
    sa.Column('renderer_key', sa.String(length=100), nullable=False),
    sa.Column('argv_prefix_json', sa.JSON(), nullable=False),
    sa.Column('params_schema_json', sa.JSON(), nullable=False),
    sa.Column('allowed_paths_policy', sa.String(length=40), nullable=False),
    sa.Column('side_effect_class', sa.String(length=20), nullable=False),
    sa.Column('network_policy', sa.String(length=20), nullable=False),
    sa.Column('egress_allowlist_json', sa.JSON(), nullable=False),
    sa.Column('resource_limits_json', sa.JSON(), nullable=False),
    sa.Column('sandbox_requirement', sa.String(length=40), nullable=False),
    sa.Column('redaction_baseline_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("allowed_paths_policy IN ('workspace_only','workspace_plus_declared_read')", name='ck_validation_capability_paths_policy'),
    sa.CheckConstraint("executable_policy IN ('project_venv_python','pinned_binary','builtin')", name='ck_validation_capability_executable_policy'),
    sa.CheckConstraint("network_policy IN ('deny','allowlist')", name='ck_validation_capability_network_policy'),
    sa.CheckConstraint("side_effect_class IN ('readonly','temp_write')", name='ck_validation_capability_side_effect'),
    sa.CheckConstraint("status IN ('active','deprecated')", name='ck_validation_capability_status'),
    sa.CheckConstraint('row_version >= 1', name='ck_validation_capability_row_version'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_id', 'capability_hash', name='uq_validation_capabilities_hash'),
    sa.UniqueConstraint('scope_id', 'capability_key', 'capability_version', name='uq_validation_capabilities_key_version')
    )
    op.create_index(op.f('ix_validation_capabilities_scope_id'), 'validation_capabilities', ['scope_id'], unique=False)
    op.create_table('artifact_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('product_run_id', sa.String(length=36), nullable=True),
    sa.Column('run_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('command_id', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('diff_patch','validation_report','generated_file','design_document','result_patch','exported_content')", name='ck_artifact_record_kind'),
    sa.CheckConstraint("status IN ('candidate','accepted','rejected','not_adopted','retained','discarded')", name='ck_artifact_record_status'),
    sa.CheckConstraint('row_version >= 1', name='ck_artifact_record_row_version'),
    sa.ForeignKeyConstraint(['product_run_id'], ['product_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_attempt_id'], ['run_attempts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_id', 'command_id', name='uq_artifact_records_command')
    )
    op.create_index('ix_artifact_records_run', 'artifact_records', ['product_run_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_artifact_records_scope_id'), 'artifact_records', ['scope_id'], unique=False)
    op.create_index('ix_artifact_records_scope_status', 'artifact_records', ['scope_id', 'status', 'updated_at'], unique=False)
    op.create_table('provenance_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=False),
    sa.Column('source_kind', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('target_kind', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('product_run_id', sa.String(length=36), nullable=True),
    sa.Column('decision_record_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("relation IN ('derived_from','generated_by','used','attributed_to','invalidated_by')", name='ck_provenance_relation'),
    sa.CheckConstraint("source_kind IN ('artifact_revision','evidence_observation','evidence_assessment','claim_evidence_adoption','requirement_waiver','validation_run','completion_claim','result_commit','tool_operation','product_run','run_attempt')", name='ck_provenance_source_kind'),
    sa.CheckConstraint("target_kind IN ('artifact_revision','evidence_observation','evidence_assessment','claim_evidence_adoption','requirement_waiver','validation_run','execution_workspace','repository_snapshot','decision_record','work_item','action_item','source_invalidation','completion_claim','result_commit','tool_operation','product_run','run_attempt')", name='ck_provenance_target_kind'),
    sa.ForeignKeyConstraint(['decision_record_id'], ['decision_records.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_run_id'], ['product_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_id', 'source_kind', 'source_id', 'relation', 'target_kind', 'target_id', name='uq_provenance_edge')
    )
    op.create_index(op.f('ix_provenance_edges_product_run_id'), 'provenance_edges', ['product_run_id'], unique=False)
    op.create_index(op.f('ix_provenance_edges_scope_id'), 'provenance_edges', ['scope_id'], unique=False)
    op.create_index('ix_provenance_run', 'provenance_edges', ['product_run_id', 'created_at'], unique=False)
    op.create_index('ix_provenance_source', 'provenance_edges', ['scope_id', 'source_kind', 'source_id'], unique=False)
    op.create_index('ix_provenance_target', 'provenance_edges', ['scope_id', 'target_kind', 'target_id'], unique=False)
    op.create_table('source_invalidations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=False),
    sa.Column('source_kind', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('invalidation_kind', sa.String(length=20), nullable=False),
    sa.Column('recovers_invalidation_id', sa.String(length=36), nullable=True),
    sa.Column('previous_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('current_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=False),
    sa.Column('resolution_decision_record_id', sa.String(length=36), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(invalidation_kind = 'recovered') = (recovers_invalidation_id IS NOT NULL)", name='ck_source_invalidation_recovered_pair'),
    sa.CheckConstraint("invalidation_kind != 'revoked' OR resolution_decision_record_id IS NOT NULL", name='ck_source_invalidation_revoked_decision'),
    sa.CheckConstraint("invalidation_kind != 'stale' OR current_fingerprint IS NOT previous_fingerprint", name='ck_source_invalidation_stale_fingerprint'),
    sa.CheckConstraint("invalidation_kind IN ('stale','unavailable','revoked','recovered')", name='ck_source_invalidation_kind'),
    sa.CheckConstraint("resolution != 'dismissed' OR resolution_decision_record_id IS NOT NULL", name='ck_source_invalidation_dismissed_decision'),
    sa.CheckConstraint("resolution IN ('pending','applied','dismissed')", name='ck_source_invalidation_resolution'),
    sa.CheckConstraint("source_kind IN ('artifact_blob','repository_snapshot','artifact_revision','evidence_observation')", name='ck_source_invalidation_source_kind'),
    sa.CheckConstraint('row_version >= 1', name='ck_source_invalidation_row_version'),
    sa.CheckConstraint('sequence >= 1', name='ck_source_invalidation_sequence'),
    sa.ForeignKeyConstraint(['recovers_invalidation_id'], ['source_invalidations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolution_decision_record_id'], ['decision_records.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_id', 'command_id', name='uq_source_invalidations_command'),
    sa.UniqueConstraint('scope_id', 'source_kind', 'source_id', 'sequence', name='uq_source_invalidation_sequence')
    )
    op.create_index('ix_source_invalidation_pending', 'source_invalidations', ['scope_id', 'resolution', 'created_at'], unique=False)
    op.create_index('ix_source_invalidation_source', 'source_invalidations', ['source_kind', 'source_id', 'resolution'], unique=False)
    op.create_index(op.f('ix_source_invalidations_scope_id'), 'source_invalidations', ['scope_id'], unique=False)
    op.create_table('artifact_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('storage_blob_id', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('supersedes_revision_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('command_id', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('revision_number >= 1', name='ck_artifact_revision_number'),
    sa.CheckConstraint('size_bytes >= 0', name='ck_artifact_revision_size'),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact_records.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['storage_blob_id'], ['artifact_blobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_revision_id'], ['artifact_revisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'command_id', name='uq_artifact_revisions_command'),
    sa.UniqueConstraint('artifact_id', 'revision_number', name='uq_artifact_revision_number')
    )
    op.create_index(op.f('ix_artifact_revisions_artifact_id'), 'artifact_revisions', ['artifact_id'], unique=False)
    op.create_index('ix_artifact_revisions_blob', 'artifact_revisions', ['storage_blob_id'], unique=False)
    op.create_index('ix_artifact_revisions_current', 'artifact_revisions', ['artifact_id', 'revision_number'], unique=False)
    op.create_index('ix_artifact_revisions_supersedes', 'artifact_revisions', ['supersedes_revision_id'], unique=False)
    op.create_table('validation_contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=False),
    sa.Column('plan_revision_id', sa.String(length=36), nullable=False),
    sa.Column('contract_hash', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('rules_json', sa.JSON(), nullable=False),
    sa.Column('requires_integration', sa.Boolean(), nullable=False),
    sa.Column('max_repair_cycles', sa.Integer(), nullable=False),
    sa.Column('network_requested', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('command_id', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_repair_cycles BETWEEN 0 AND 5', name='ck_validation_contract_repair_cycles'),
    sa.ForeignKeyConstraint(['plan_revision_id'], ['task_plan_revisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_id', 'command_id', name='uq_validation_contracts_command')
    )
    op.create_index('ix_validation_contracts_hash', 'validation_contracts', ['scope_id', 'contract_hash', 'created_at'], unique=False)
    op.create_index(op.f('ix_validation_contracts_scope_id'), 'validation_contracts', ['scope_id'], unique=False)
    op.create_table('completion_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=False),
    sa.Column('subject_kind', sa.String(length=40), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=False),
    sa.Column('expected_subject_version', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=False),
    sa.Column('target_transition', sa.String(length=40), nullable=False),
    sa.Column('target_state', sa.String(length=32), nullable=False),
    sa.Column('artifact_revision_id', sa.String(length=36), nullable=True),
    sa.Column('expected_artifact_record_version', sa.Integer(), nullable=True),
    sa.Column('repository_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('applicability_policy', sa.String(length=40), nullable=False),
    sa.Column('validation_contract_id', sa.String(length=36), nullable=True),
    sa.Column('claim_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision_record_id', sa.String(length=36), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("applicability_policy != 'must_match_current_target' OR repository_snapshot_id IS NOT NULL", name='ck_completion_claim_applicability_snapshot'),
    sa.CheckConstraint("status = 'candidate' OR decision_record_id IS NOT NULL", name='ck_completion_claim_resolved_decision'),
    sa.CheckConstraint("status IN ('candidate','committed','rejected','superseded')", name='ck_completion_claim_status'),
    sa.CheckConstraint('(artifact_revision_id IS NULL AND expected_artifact_record_version IS NULL) OR (artifact_revision_id IS NOT NULL AND expected_artifact_record_version IS NOT NULL)', name='ck_completion_claim_artifact_consistency'),
    sa.CheckConstraint('expected_artifact_record_version IS NULL OR expected_artifact_record_version >= 1', name='ck_completion_claim_expected_artifact_version'),
    sa.CheckConstraint('row_version >= 1', name='ck_completion_claim_row_version'),
    sa.ForeignKeyConstraint(['artifact_revision_id'], ['artifact_revisions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decision_record_id'], ['decision_records.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_snapshot_id'], ['repository_snapshots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['validation_contract_id'], ['validation_contracts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_revision_id', name='uq_completion_claim_artifact_revision'),
    sa.UniqueConstraint('scope_id', 'command_id', name='uq_completion_claims_command')
    )
    op.create_index('ix_completion_claims_artifact', 'completion_claims', ['artifact_revision_id'], unique=False)
    op.create_index('ix_completion_claims_hash', 'completion_claims', ['scope_id', 'claim_hash', 'created_at'], unique=False)
    op.create_index(op.f('ix_completion_claims_scope_id'), 'completion_claims', ['scope_id'], unique=False)
    op.create_index('ix_completion_claims_snapshot', 'completion_claims', ['repository_snapshot_id', 'status'], unique=False)
    op.create_index('ix_completion_claims_subject', 'completion_claims', ['subject_kind', 'subject_id', 'status', 'updated_at'], unique=False)
    op.create_table('completion_claim_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=False),
    sa.Column('completion_claim_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_index', sa.Integer(), nullable=False),
    sa.Column('requirement_kind', sa.String(length=40), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contract_rule_ordinal', sa.Integer(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("requirement_kind IN ('validation_result','file_hash_match','tool_receipt','model_output_adoption','human_confirmation','external_observation')", name='ck_claim_requirement_kind'),
    sa.CheckConstraint('requirement_index >= 0', name='ck_claim_requirement_index'),
    sa.ForeignKeyConstraint(['completion_claim_id'], ['completion_claims.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('completion_claim_id', 'requirement_index', name='uq_claim_requirement_index')
    )
    op.create_index('ix_claim_requirements_claim', 'completion_claim_requirements', ['completion_claim_id'], unique=False)
    op.create_index(op.f('ix_completion_claim_requirements_completion_claim_id'), 'completion_claim_requirements', ['completion_claim_id'], unique=False)
    op.create_index(op.f('ix_completion_claim_requirements_scope_id'), 'completion_claim_requirements', ['scope_id'], unique=False)
    op.create_table('result_commits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=False),
    sa.Column('completion_claim_id', sa.String(length=36), nullable=False),
    sa.Column('commit_status', sa.String(length=20), nullable=False),
    sa.Column('artifact_disposition', sa.String(length=20), nullable=False),
    sa.Column('pre_commit_validity_check_passed', sa.Boolean(), nullable=False),
    sa.Column('decision_record_id', sa.String(length=36), nullable=False),
    sa.Column('committed_subject_state', sa.String(length=32), nullable=True),
    sa.Column('command_id', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("artifact_disposition IN ('accepted','rejected','not_adopted','none')", name='ck_result_commit_artifact_disposition'),
    sa.CheckConstraint("commit_status = 'rejected' OR pre_commit_validity_check_passed", name='ck_result_commit_validity'),
    sa.CheckConstraint("commit_status IN ('accepted','rejected','waived')", name='ck_result_commit_status'),
    sa.ForeignKeyConstraint(['completion_claim_id'], ['completion_claims.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decision_record_id'], ['decision_records.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('completion_claim_id', name='uq_result_commits_claim'),
    sa.UniqueConstraint('scope_id', 'command_id', name='uq_result_commits_command')
    )
    op.create_index(op.f('ix_result_commits_scope_id'), 'result_commits', ['scope_id'], unique=False)
    op.create_index('ix_result_commits_status', 'result_commits', ['commit_status', 'created_at'], unique=False)
    op.create_table('validation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('repository_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('validation_contract_id', sa.String(length=36), nullable=False),
    sa.Column('contract_hash', sa.String(length=64), nullable=False),
    sa.Column('rule_ordinal', sa.Integer(), nullable=False),
    sa.Column('capability_key', sa.String(length=80), nullable=False),
    sa.Column('capability_version', sa.String(length=40), nullable=False),
    sa.Column('capability_hash', sa.String(length=64), nullable=False),
    sa.Column('resolved_executable_hash', sa.String(length=64), nullable=False),
    sa.Column('environment_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('expanded_argv_json', sa.JSON(), nullable=False),
    sa.Column('expanded_argv_hash', sa.String(length=64), nullable=False),
    sa.Column('working_dir', sa.String(length=240), nullable=False),
    sa.Column('repair_cycle', sa.Integer(), nullable=False),
    sa.Column('runtime_job_id', sa.String(length=36), nullable=False),
    sa.Column('run_attempt_id', sa.String(length=36), nullable=False),
    sa.Column('runtime_lease_epoch', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('report_artifact_revision_id', sa.String(length=36), nullable=True),
    sa.Column('stdout_tail', sa.Text(), nullable=True),
    sa.Column('stderr_tail', sa.Text(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.String(length=160), nullable=False),
    sa.Column('outcome_command_id', sa.String(length=160), nullable=True),
    sa.Column('outcome_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status != 'pending' OR (started_at IS NULL AND finished_at IS NULL)) AND (status != 'running' OR (started_at IS NOT NULL AND finished_at IS NULL)) AND (status IN ('pending','running') OR finished_at IS NOT NULL) AND (status NOT IN ('passed','failed') OR exit_code IS NOT NULL)", name='ck_validation_run_state_consistency'),
    sa.CheckConstraint("status IN ('pending','running','passed','failed','timeout','error','cancelled','outcome_unknown')", name='ck_validation_run_status'),
    sa.CheckConstraint('duration_ms IS NULL OR duration_ms >= 0', name='ck_validation_run_duration'),
    sa.CheckConstraint('repair_cycle >= 0', name='ck_validation_run_repair_cycle'),
    sa.CheckConstraint('row_version >= 1', name='ck_validation_run_row_version'),
    sa.ForeignKeyConstraint(['report_artifact_revision_id'], ['artifact_revisions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_snapshot_id'], ['repository_snapshots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_attempt_id'], ['run_attempts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['runtime_job_id'], ['runtime_jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['validation_contract_id'], ['validation_contracts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['execution_workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_id', 'command_id', name='uq_validation_runs_command'),
    sa.UniqueConstraint('scope_id', 'outcome_command_id', name='uq_validation_runs_outcome_command')
    )
    op.create_index('ix_validation_runs_attempt', 'validation_runs', ['run_attempt_id', 'runtime_lease_epoch'], unique=False)
    op.create_index('ix_validation_runs_contract', 'validation_runs', ['validation_contract_id', 'rule_ordinal', 'repair_cycle'], unique=False)
    op.create_index(op.f('ix_validation_runs_run_attempt_id'), 'validation_runs', ['run_attempt_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_scope_id'), 'validation_runs', ['scope_id'], unique=False)
    op.create_index('ix_validation_runs_status', 'validation_runs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_validation_runs_validation_contract_id'), 'validation_runs', ['validation_contract_id'], unique=False)
    op.create_index('ix_validation_runs_workspace', 'validation_runs', ['workspace_id', 'status'], unique=False)
    op.create_table('evidence_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('subject_kind', sa.String(length=40), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=False),
    sa.Column('validation_run_id', sa.String(length=36), nullable=True),
    sa.Column('tool_operation_id', sa.String(length=36), nullable=True),
    sa.Column('model_call_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('repository_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_revision_id', sa.String(length=36), nullable=True),
    sa.Column('product_run_id', sa.String(length=36), nullable=True),
    sa.Column('run_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('decision_record_id', sa.String(length=36), nullable=True),
    sa.Column('validity', sa.String(length=32), nullable=False),
    sa.Column('verification_method', sa.String(length=80), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('command_id', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('validation_result','file_hash_match','tool_receipt','model_output_adoption','human_confirmation','external_observation')", name='ck_evidence_observation_kind'),
    sa.CheckConstraint("subject_kind IN ('work_item','action_item','artifact_revision')", name='ck_evidence_observation_subject_kind'),
    sa.CheckConstraint("validity IN ('valid','stale','unavailable','revoked','unverifiable')", name='ck_evidence_observation_validity'),
    sa.CheckConstraint('product_run_id IS NOT NULL OR run_attempt_id IS NOT NULL OR tool_operation_id IS NOT NULL OR model_call_attempt_id IS NOT NULL OR validation_run_id IS NOT NULL OR repository_snapshot_id IS NOT NULL OR decision_record_id IS NOT NULL', name='ck_evidence_observation_has_source'),
    sa.CheckConstraint('row_version >= 1', name='ck_evidence_observation_row_version'),
    sa.ForeignKeyConstraint(['artifact_revision_id'], ['artifact_revisions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decision_record_id'], ['decision_records.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_call_attempt_id'], ['model_call_attempts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_run_id'], ['product_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_snapshot_id'], ['repository_snapshots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_attempt_id'], ['run_attempts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tool_operation_id'], ['tool_operations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_id', 'command_id', name='uq_evidence_observations_command')
    )
    op.create_index('ix_evidence_obs_run', 'evidence_observations', ['product_run_id', 'created_at'], unique=False)
    op.create_index('ix_evidence_obs_subject', 'evidence_observations', ['subject_kind', 'subject_id', 'validity'], unique=False)
    op.create_index('ix_evidence_obs_validation_run', 'evidence_observations', ['validation_run_id'], unique=False)
    op.create_index('ix_evidence_obs_validity', 'evidence_observations', ['validity', 'updated_at'], unique=False)
    op.create_index(op.f('ix_evidence_observations_artifact_revision_id'), 'evidence_observations', ['artifact_revision_id'], unique=False)
    op.create_index(op.f('ix_evidence_observations_scope_id'), 'evidence_observations', ['scope_id'], unique=False)
    op.create_table('requirement_waivers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('decision_record_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('command_id', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_record_id'], ['decision_records.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_id'], ['completion_claim_requirements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', name='uq_waiver_requirement'),
    sa.UniqueConstraint('scope_id', 'command_id', name='uq_waivers_command')
    )
    op.create_index(op.f('ix_requirement_waivers_requirement_id'), 'requirement_waivers', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_requirement_waivers_scope_id'), 'requirement_waivers', ['scope_id'], unique=False)
    op.create_table('evidence_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('assessment_sequence', sa.Integer(), nullable=False),
    sa.Column('supersedes_assessment_id', sa.String(length=36), nullable=True),
    sa.Column('assessor_kind', sa.String(length=20), nullable=False),
    sa.Column('assessor_run_id', sa.String(length=36), nullable=True),
    sa.Column('assessor_principal_id', sa.String(length=100), nullable=True),
    sa.Column('decision_record_id', sa.String(length=36), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('command_id', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("assessor_kind IN ('validator','workflow','human')", name='ck_assessment_assessor_kind'),
    sa.CheckConstraint("verdict IN ('supports','refutes','inconclusive')", name='ck_assessment_verdict'),
    sa.CheckConstraint('assessment_sequence >= 1', name='ck_assessment_sequence'),
    sa.ForeignKeyConstraint(['assessor_run_id'], ['product_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decision_record_id'], ['decision_records.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['observation_id'], ['evidence_observations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_id'], ['completion_claim_requirements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_assessment_id'], ['evidence_assessments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id', 'requirement_id', name='uq_assessment_observation_requirement'),
    sa.UniqueConstraint('requirement_id', 'assessment_sequence', name='uq_assessment_requirement_sequence'),
    sa.UniqueConstraint('scope_id', 'command_id', name='uq_assessments_command')
    )
    op.create_index('ix_assessments_observation', 'evidence_assessments', ['observation_id'], unique=False)
    op.create_index('ix_assessments_requirement', 'evidence_assessments', ['requirement_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_evidence_assessments_observation_id'), 'evidence_assessments', ['observation_id'], unique=False)
    op.create_index(op.f('ix_evidence_assessments_requirement_id'), 'evidence_assessments', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_evidence_assessments_scope_id'), 'evidence_assessments', ['scope_id'], unique=False)
    op.create_table('claim_evidence_adoptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=100), nullable=False),
    sa.Column('completion_claim_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('decision_record_id', sa.String(length=36), nullable=False),
    sa.Column('command_id', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['evidence_assessments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['completion_claim_id'], ['completion_claims.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decision_record_id'], ['decision_records.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_id'], ['completion_claim_requirements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('completion_claim_id', 'requirement_id', name='uq_adoption_claim_requirement'),
    sa.UniqueConstraint('scope_id', 'command_id', name='uq_adoptions_command')
    )
    op.create_index('ix_adoptions_assessment', 'claim_evidence_adoptions', ['assessment_id'], unique=False)
    op.create_index('ix_adoptions_claim', 'claim_evidence_adoptions', ['completion_claim_id'], unique=False)
    op.create_index(op.f('ix_claim_evidence_adoptions_completion_claim_id'), 'claim_evidence_adoptions', ['completion_claim_id'], unique=False)
    op.create_index(op.f('ix_claim_evidence_adoptions_scope_id'), 'claim_evidence_adoptions', ['scope_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_evidence_adoptions_scope_id'), table_name='claim_evidence_adoptions')
    op.drop_index(op.f('ix_claim_evidence_adoptions_completion_claim_id'), table_name='claim_evidence_adoptions')
    op.drop_index('ix_adoptions_claim', table_name='claim_evidence_adoptions')
    op.drop_index('ix_adoptions_assessment', table_name='claim_evidence_adoptions')
    op.drop_table('claim_evidence_adoptions')
    op.drop_index(op.f('ix_evidence_assessments_scope_id'), table_name='evidence_assessments')
    op.drop_index(op.f('ix_evidence_assessments_requirement_id'), table_name='evidence_assessments')
    op.drop_index(op.f('ix_evidence_assessments_observation_id'), table_name='evidence_assessments')
    op.drop_index('ix_assessments_requirement', table_name='evidence_assessments')
    op.drop_index('ix_assessments_observation', table_name='evidence_assessments')
    op.drop_table('evidence_assessments')
    op.drop_index(op.f('ix_requirement_waivers_scope_id'), table_name='requirement_waivers')
    op.drop_index(op.f('ix_requirement_waivers_requirement_id'), table_name='requirement_waivers')
    op.drop_table('requirement_waivers')
    op.drop_index(op.f('ix_evidence_observations_scope_id'), table_name='evidence_observations')
    op.drop_index(op.f('ix_evidence_observations_artifact_revision_id'), table_name='evidence_observations')
    op.drop_index('ix_evidence_obs_validity', table_name='evidence_observations')
    op.drop_index('ix_evidence_obs_validation_run', table_name='evidence_observations')
    op.drop_index('ix_evidence_obs_subject', table_name='evidence_observations')
    op.drop_index('ix_evidence_obs_run', table_name='evidence_observations')
    op.drop_table('evidence_observations')
    op.drop_index('ix_validation_runs_workspace', table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_validation_contract_id'), table_name='validation_runs')
    op.drop_index('ix_validation_runs_status', table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_scope_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_run_attempt_id'), table_name='validation_runs')
    op.drop_index('ix_validation_runs_contract', table_name='validation_runs')
    op.drop_index('ix_validation_runs_attempt', table_name='validation_runs')
    op.drop_table('validation_runs')
    op.drop_index('ix_result_commits_status', table_name='result_commits')
    op.drop_index(op.f('ix_result_commits_scope_id'), table_name='result_commits')
    op.drop_table('result_commits')
    op.drop_index(op.f('ix_completion_claim_requirements_scope_id'), table_name='completion_claim_requirements')
    op.drop_index(op.f('ix_completion_claim_requirements_completion_claim_id'), table_name='completion_claim_requirements')
    op.drop_index('ix_claim_requirements_claim', table_name='completion_claim_requirements')
    op.drop_table('completion_claim_requirements')
    op.drop_index('ix_completion_claims_subject', table_name='completion_claims')
    op.drop_index('ix_completion_claims_snapshot', table_name='completion_claims')
    op.drop_index(op.f('ix_completion_claims_scope_id'), table_name='completion_claims')
    op.drop_index('ix_completion_claims_hash', table_name='completion_claims')
    op.drop_index('ix_completion_claims_artifact', table_name='completion_claims')
    op.drop_table('completion_claims')
    op.drop_index(op.f('ix_validation_contracts_scope_id'), table_name='validation_contracts')
    op.drop_index('ix_validation_contracts_hash', table_name='validation_contracts')
    op.drop_table('validation_contracts')
    op.drop_index('ix_artifact_revisions_supersedes', table_name='artifact_revisions')
    op.drop_index('ix_artifact_revisions_current', table_name='artifact_revisions')
    op.drop_index('ix_artifact_revisions_blob', table_name='artifact_revisions')
    op.drop_index(op.f('ix_artifact_revisions_artifact_id'), table_name='artifact_revisions')
    op.drop_table('artifact_revisions')
    op.drop_index(op.f('ix_source_invalidations_scope_id'), table_name='source_invalidations')
    op.drop_index('ix_source_invalidation_source', table_name='source_invalidations')
    op.drop_index('ix_source_invalidation_pending', table_name='source_invalidations')
    op.drop_table('source_invalidations')
    op.drop_index('ix_provenance_target', table_name='provenance_edges')
    op.drop_index('ix_provenance_source', table_name='provenance_edges')
    op.drop_index('ix_provenance_run', table_name='provenance_edges')
    op.drop_index(op.f('ix_provenance_edges_scope_id'), table_name='provenance_edges')
    op.drop_index(op.f('ix_provenance_edges_product_run_id'), table_name='provenance_edges')
    op.drop_table('provenance_edges')
    op.drop_index('ix_artifact_records_scope_status', table_name='artifact_records')
    op.drop_index(op.f('ix_artifact_records_scope_id'), table_name='artifact_records')
    op.drop_index('ix_artifact_records_run', table_name='artifact_records')
    op.drop_table('artifact_records')
    op.drop_index(op.f('ix_validation_capabilities_scope_id'), table_name='validation_capabilities')
    op.drop_table('validation_capabilities')
    op.drop_index(op.f('ix_artifact_blobs_scope_id'), table_name='artifact_blobs')
    op.drop_index('ix_artifact_blobs_scope_gc', table_name='artifact_blobs')
    op.drop_index('ix_artifact_blobs_scope_created', table_name='artifact_blobs')
    op.drop_table('artifact_blobs')
    # ### end Alembic commands ###
